INSERT INTO "public"."brands" ("id", "name", "gender", "type") VALUES
(743, 'Chanel', 'femme', 'vetements'),
(744, 'Chanel', 'femme', 'chaussures'),
(745, 'Christian Dior', 'femme', 'vetements'),
(746, 'Christian Dior', 'femme', 'chaussures'),
(747, 'Christian Dior', 'femme', 'accessoires'),
(748, 'Gucci', 'femme', 'vetements'),
(749, 'Gucci', 'femme', 'chaussures'),
(750, 'Saint Laurent', 'femme', 'vetements'),
(751, 'Saint Laurent', 'femme', 'chaussures'),
(752, 'Balenciaga', 'femme', 'vetements'),
(753, 'Balenciaga', 'femme', 'chaussures'),
(754, 'Valentino', 'femme', 'vetements'),
(755, 'Valentino', 'femme', 'chaussures'),
(756, 'Givenchy', 'femme', 'vetements'),
(757, 'Givenchy', 'femme', 'chaussures'),
(758, 'Celine', 'femme', 'vetements'),
(759, 'Celine', 'femme', 'chaussures'),
(760, 'Celine', 'femme', 'sacs'),
(761, 'Celine', 'femme', 'accessoires'),
(762, 'Bottega Veneta', 'femme', 'vetements'),
(763, 'Bottega Veneta', 'femme', 'chaussures'),
(764, 'Loewe', 'femme', 'vetements'),
(765, 'Loewe', 'femme', 'chaussures'),
(766, 'Loewe', 'femme', 'accessoires'),
(767, 'Prada', 'femme', 'vetements'),
(768, 'Miu Miu', 'femme', 'vetements'),
(769, 'Miu Miu', 'femme', 'chaussures'),
(770, 'Miu Miu', 'femme', 'accessoires'),
(771, 'Versace', 'femme', 'vetements'),
(772, 'Versace', 'femme', 'chaussures'),
(773, 'Versace', 'femme', 'sacs'),
(774, 'Versace', 'femme', 'accessoires'),
(775, 'Fendi', 'femme', 'vetements'),
(776, 'Fendi', 'femme', 'chaussures'),
(777, 'Balmain', 'femme', 'vetements'),
(778, 'Balmain', 'femme', 'chaussures'),
(779, 'Balmain', 'femme', 'sacs'),
(780, 'Balmain', 'femme', 'accessoires'),
(781, 'Alexander McQueen', 'femme', 'vetements'),
(782, 'Alexander McQueen', 'femme', 'chaussures'),
(783, 'Alexander McQueen', 'femme', 'accessoires'),
(784, 'Stella McCartney', 'femme', 'vetements'),
(785, 'Stella McCartney', 'femme', 'chaussures'),
(786, 'Stella McCartney', 'femme', 'accessoires'),
(787, 'Isabel Marant', 'femme', 'vetements'),
(788, 'Isabel Marant', 'femme', 'chaussures'),
(789, 'Isabel Marant', 'femme', 'sacs'),
(790, 'Isabel Marant', 'femme', 'accessoires'),
(791, 'Jacquemus', 'femme', 'vetements'),
(792, 'Jacquemus', 'femme', 'chaussures'),
(793, 'Zimmermann', 'femme', 'vetements'),
(794, 'Zimmermann', 'femme', 'chaussures'),
(795, 'Zimmermann', 'femme', 'sacs'),
(796, 'Zimmermann', 'femme', 'accessoires'),
(797, 'Alaïa', 'femme', 'vetements'),
(798, 'Alaïa', 'femme', 'chaussures'),
(799, 'Alaïa', 'femme', 'accessoires'),
(800, 'Lanvin', 'femme', 'vetements'),
(801, 'Lanvin', 'femme', 'chaussures'),
(802, 'Lanvin', 'femme', 'sacs'),
(803, 'Lanvin', 'femme', 'accessoires'),
(804, 'Rochas', 'femme', 'vetements'),
(805, 'Rochas', 'femme', 'chaussures'),
(806, 'Rochas', 'femme', 'sacs'),
(807, 'Rochas', 'femme', 'accessoires'),
(808, 'Maison Margiela', 'femme', 'vetements'),
(809, 'Maison Margiela', 'femme', 'chaussures'),
(810, 'Maison Margiela', 'femme', 'sacs'),
(811, 'Maison Margiela', 'femme', 'accessoires'),
(812, 'Giambattista Valli', 'femme', 'vetements'),
(813, 'Giambattista Valli', 'femme', 'chaussures'),
(814, 'Giambattista Valli', 'femme', 'sacs'),
(815, 'Giambattista Valli', 'femme', 'accessoires'),
(816, 'Elie Saab', 'femme', 'vetements'),
(817, 'Elie Saab', 'femme', 'chaussures'),
(818, 'Elie Saab', 'femme', 'sacs'),
(819, 'Elie Saab', 'femme', 'accessoires'),
(820, 'Zuhair Murad', 'femme', 'vetements'),
(821, 'Zuhair Murad', 'femme', 'chaussures'),
(822, 'Zuhair Murad', 'femme', 'sacs'),
(823, 'Zuhair Murad', 'femme', 'accessoires'),
(824, 'Georges Chakra', 'femme', 'vetements'),
(825, 'Georges Chakra', 'femme', 'chaussures'),
(826, 'Georges Chakra', 'femme', 'sacs'),
(827, 'Georges Chakra', 'femme', 'accessoires'),
(828, 'Oscar de la Renta', 'femme', 'vetements'),
(829, 'Oscar de la Renta', 'femme', 'chaussures'),
(830, 'Oscar de la Renta', 'femme', 'sacs'),
(831, 'Oscar de la Renta', 'femme', 'accessoires'),
(832, 'Carolina Herrera', 'femme', 'vetements'),
(833, 'Carolina Herrera', 'femme', 'chaussures'),
(834, 'Carolina Herrera', 'femme', 'sacs'),
(835, 'Carolina Herrera', 'femme', 'accessoires'),
(836, 'Marchesa', 'femme', 'vetements'),
(837, 'Marchesa', 'femme', 'chaussures'),
(838, 'Marchesa', 'femme', 'sacs'),
(839, 'Marchesa', 'femme', 'accessoires'),
(840, 'Max Mara', 'femme', 'vetements'),
(841, 'Max Mara', 'femme', 'chaussures'),
(842, 'Max Mara', 'femme', 'sacs'),
(843, 'Max Mara', 'femme', 'accessoires'),
(844, 'Escada', 'femme', 'vetements'),
(845, 'Escada', 'femme', 'chaussures'),
(846, 'Escada', 'femme', 'sacs'),
(847, 'Escada', 'femme', 'accessoires'),
(848, 'Akris', 'femme', 'vetements'),
(849, 'Akris', 'femme', 'chaussures'),
(850, 'Emilio Pucci', 'femme', 'vetements'),
(851, 'Emilio Pucci', 'femme', 'chaussures'),
(852, 'Emilio Pucci', 'femme', 'sacs'),
(853, 'Emilio Pucci', 'femme', 'accessoires'),
(854, 'Missoni', 'femme', 'vetements'),
(855, 'Missoni', 'femme', 'chaussures'),
(856, 'Missoni', 'femme', 'sacs'),
(857, 'Missoni', 'femme', 'accessoires'),
(858, 'Etro', 'femme', 'vetements'),
(859, 'Etro', 'femme', 'chaussures'),
(860, 'Etro', 'femme', 'sacs'),
(861, 'Etro', 'femme', 'accessoires'),
(862, 'Moschino', 'femme', 'vetements'),
(863, 'Moschino', 'femme', 'chaussures'),
(864, 'Moschino', 'femme', 'sacs'),
(865, 'Moschino', 'femme', 'accessoires'),
(866, 'Roberto Cavalli', 'femme', 'vetements'),
(867, 'Roberto Cavalli', 'femme', 'chaussures'),
(868, 'Roberto Cavalli', 'femme', 'sacs'),
(869, 'Roberto Cavalli', 'femme', 'accessoires'),
(870, 'Dsquared2', 'femme', 'vetements'),
(871, 'Dsquared2', 'femme', 'chaussures'),
(872, 'Dsquared2', 'femme', 'sacs'),
(873, 'Dsquared2', 'femme', 'accessoires'),
(874, 'Philosophy di Lorenzo Serafini', 'femme', 'vetements'),
(875, 'Philosophy di Lorenzo Serafini', 'femme', 'chaussures'),
(876, 'Philosophy di Lorenzo Serafini', 'femme', 'sacs'),
(877, 'Philosophy di Lorenzo Serafini', 'femme', 'accessoires'),
(878, 'Pinko', 'femme', 'vetements'),
(879, 'Pinko', 'femme', 'chaussures'),
(880, 'Pinko', 'femme', 'sacs'),
(881, 'Pinko', 'femme', 'accessoires'),
(882, 'Patrizia Pepe', 'femme', 'vetements'),
(883, 'Patrizia Pepe', 'femme', 'chaussures'),
(884, 'Patrizia Pepe', 'femme', 'sacs'),
(885, 'Patrizia Pepe', 'femme', 'accessoires'),
(886, 'Self-Portrait', 'femme', 'vetements'),
(887, 'Self-Portrait', 'femme', 'chaussures'),
(888, 'Self-Portrait', 'femme', 'sacs'),
(889, 'Self-Portrait', 'femme', 'accessoires'),
(890, 'Rixo', 'femme', 'vetements'),
(891, 'Rixo', 'femme', 'chaussures'),
(892, 'Rixo', 'femme', 'sacs'),
(893, 'Rixo', 'femme', 'accessoires'),
(894, 'Reformation', 'femme', 'vetements'),
(895, 'Reformation', 'femme', 'chaussures'),
(896, 'Reformation', 'femme', 'sacs'),
(897, 'Reformation', 'femme', 'accessoires'),
(898, 'Rotate Birger Christensen', 'femme', 'vetements'),
(899, 'Rotate Birger Christensen', 'femme', 'chaussures'),
(900, 'Rotate Birger Christensen', 'femme', 'sacs'),
(901, 'Rotate Birger Christensen', 'femme', 'accessoires'),
(902, 'Ganni', 'femme', 'vetements'),
(903, 'Ganni', 'femme', 'chaussures'),
(904, 'Ganni', 'femme', 'sacs'),
(905, 'Ganni', 'femme', 'accessoires'),
(906, 'Sandro', 'femme', 'vetements'),
(907, 'Sandro', 'femme', 'chaussures'),
(908, 'Sandro', 'femme', 'sacs'),
(909, 'Sandro', 'femme', 'accessoires'),
(910, 'Maje', 'femme', 'vetements'),
(911, 'Maje', 'femme', 'chaussures'),
(912, 'Maje', 'femme', 'sacs'),
(913, 'Maje', 'femme', 'accessoires'),
(914, 'Ba&sh', 'femme', 'vetements'),
(915, 'Ba&sh', 'femme', 'chaussures'),
(916, 'Ba&sh', 'femme', 'sacs'),
(917, 'Ba&sh', 'femme', 'accessoires'),
(918, 'Claudie Pierlot', 'femme', 'vetements'),
(919, 'Claudie Pierlot', 'femme', 'chaussures'),
(920, 'Claudie Pierlot', 'femme', 'sacs'),
(921, 'Claudie Pierlot', 'femme', 'accessoires'),
(922, 'The Kooples', 'femme', 'vetements'),
(923, 'The Kooples', 'femme', 'sacs'),
(924, 'The Kooples', 'femme', 'accessoires'),
(925, 'A.P.C.', 'femme', 'vetements'),
(926, 'A.P.C.', 'femme', 'chaussures'),
(927, 'Ami Paris', 'femme', 'vetements'),
(928, 'Ami Paris', 'femme', 'chaussures'),
(929, 'Ami Paris', 'femme', 'sacs'),
(930, 'Ami Paris', 'femme', 'accessoires'),
(931, 'Acne Studios', 'femme', 'vetements'),
(932, 'Acne Studios', 'femme', 'chaussures'),
(933, 'Acne Studios', 'femme', 'sacs'),
(934, 'Acne Studios', 'femme', 'accessoires'),
(935, 'COS', 'femme', 'chaussures'),
(936, 'COS', 'femme', 'sacs'),
(937, 'COS', 'femme', 'accessoires'),
(938, '& Other Stories', 'femme', 'vetements'),
(939, '& Other Stories', 'femme', 'chaussures'),
(940, '& Other Stories', 'femme', 'sacs'),
(941, '& Other Stories', 'femme', 'accessoires'),
(942, 'Nanushka', 'femme', 'vetements'),
(943, 'Nanushka', 'femme', 'chaussures'),
(944, 'Nanushka', 'femme', 'sacs'),
(945, 'Nanushka', 'femme', 'accessoires'),
(946, 'Toteme', 'femme', 'vetements'),
(947, 'Toteme', 'femme', 'chaussures'),
(948, 'Toteme', 'femme', 'sacs'),
(949, 'Toteme', 'femme', 'accessoires'),
(950, 'Theory', 'femme', 'vetements'),
(951, 'Theory', 'femme', 'chaussures'),
(952, 'Theory', 'femme', 'sacs'),
(953, 'Theory', 'femme', 'accessoires'),
(954, 'Equipment', 'femme', 'vetements'),
(955, 'Equipment', 'femme', 'chaussures'),
(956, 'Equipment', 'femme', 'sacs'),
(957, 'Equipment', 'femme', 'accessoires'),
(958, 'Vince', 'femme', 'vetements'),
(959, 'Vince', 'femme', 'chaussures'),
(960, 'Vince', 'femme', 'sacs'),
(961, 'Vince', 'femme', 'accessoires'),
(962, 'IRO', 'femme', 'vetements'),
(963, 'IRO', 'femme', 'chaussures'),
(964, 'IRO', 'femme', 'sacs'),
(965, 'IRO', 'femme', 'accessoires'),
(966, 'Zadig & Voltaire', 'femme', 'vetements'),
(967, 'Zadig & Voltaire', 'femme', 'chaussures'),
(968, 'Zadig & Voltaire', 'femme', 'sacs'),
(969, 'Zadig & Voltaire', 'femme', 'accessoires'),
(970, 'Comptoir des Cotonniers', 'femme', 'vetements'),
(971, 'Comptoir des Cotonniers', 'femme', 'chaussures'),
(972, 'Comptoir des Cotonniers', 'femme', 'sacs'),
(973, 'Comptoir des Cotonniers', 'femme', 'accessoires'),
(974, 'Gerard Darel', 'femme', 'vetements'),
(975, 'Gerard Darel', 'femme', 'chaussures'),
(976, 'Gerard Darel', 'femme', 'sacs'),
(977, 'Gerard Darel', 'femme', 'accessoires'),
(978, 'Marella', 'femme', 'vetements'),
(979, 'Marella', 'femme', 'chaussures'),
(980, 'Marella', 'femme', 'sacs'),
(981, 'Marella', 'femme', 'accessoires'),
(982, 'Luisa Spagnoli', 'femme', 'vetements'),
(983, 'Luisa Spagnoli', 'femme', 'chaussures'),
(984, 'Luisa Spagnoli', 'femme', 'sacs'),
(985, 'Luisa Spagnoli', 'femme', 'accessoires'),
(986, 'Blumarine', 'femme', 'vetements'),
(987, 'Blumarine', 'femme', 'chaussures'),
(988, 'Blumarine', 'femme', 'sacs'),
(989, 'Blumarine', 'femme', 'accessoires'),
(990, 'Alberta Ferretti', 'femme', 'vetements'),
(991, 'Alberta Ferretti', 'femme', 'chaussures'),
(992, 'Alberta Ferretti', 'femme', 'sacs'),
(993, 'Alberta Ferretti', 'femme', 'accessoires'),
(994, 'Elisabetta Franchi', 'femme', 'vetements'),
(995, 'Elisabetta Franchi', 'femme', 'chaussures'),
(996, 'Elisabetta Franchi', 'femme', 'sacs'),
(997, 'Elisabetta Franchi', 'femme', 'accessoires'),
(998, 'Moschino Cheap and Chic', 'femme', 'vetements'),
(999, 'Moschino Cheap and Chic', 'femme', 'chaussures'),
(1000, 'Moschino Cheap and Chic', 'femme', 'sacs'),
(1001, 'Moschino Cheap and Chic', 'femme', 'accessoires'),
(1002, 'MM6 Maison Margiela', 'femme', 'vetements'),
(1003, 'MM6 Maison Margiela', 'femme', 'chaussures'),
(1004, 'MM6 Maison Margiela', 'femme', 'sacs'),
(1005, 'MM6 Maison Margiela', 'femme', 'accessoires'),
(1006, 'Vivienne Westwood', 'femme', 'vetements'),
(1007, 'Vivienne Westwood', 'femme', 'chaussures'),
(1008, 'Vivienne Westwood', 'femme', 'sacs'),
(1009, 'Vivienne Westwood', 'femme', 'accessoires'),
(1010, 'Comme des Garçons', 'femme', 'vetements'),
(1011, 'Comme des Garçons', 'femme', 'chaussures'),
(1012, 'Comme des Garçons', 'femme', 'sacs'),
(1013, 'Comme des Garçons', 'femme', 'accessoires'),
(1014, 'Issey Miyake', 'femme', 'vetements'),
(1015, 'Issey Miyake', 'femme', 'chaussures'),
(1016, 'Issey Miyake', 'femme', 'sacs'),
(1017, 'Issey Miyake', 'femme', 'accessoires'),
(1018, 'Kate Spade', 'femme', 'sacs'),
(1019, 'Tory Burch', 'femme', 'sacs'),
(1020, 'Furla', 'femme', 'sacs'),
(1021, 'Coccinelle', 'femme', 'sacs'),
(1022, 'Mulberry', 'femme', 'sacs'),
(1023, 'Strathberry', 'femme', 'sacs'),
(1024, 'Polène', 'femme', 'sacs'),
(1025, 'Mansur Gavriel', 'femme', 'sacs'),
(1026, 'Alexander Wang', 'femme', 'sacs'),
(1027, 'Goyard', 'femme', 'sacs'),
(1028, 'Moynat', 'femme', 'sacs'),
(1029, 'MCM', 'femme', 'sacs'),
(1030, 'Lancel', 'femme', 'sacs'),
(1031, 'By Far', 'femme', 'sacs'),
(1032, 'Staud', 'femme', 'sacs'),
(1033, 'Simon Miller', 'femme', 'sacs'),
(1034, 'Wandler', 'femme', 'sacs'),
(1035, 'Hereu', 'femme', 'sacs'),
(1036, 'Vasic', 'femme', 'sacs'),
(1037, 'Manu Atelier', 'femme', 'sacs'),
(1038, 'Cult Gaia', 'femme', 'sacs'),
(1039, 'Dragon Diffusion', 'femme', 'sacs'),
(1040, 'DeMellier', 'femme', 'sacs'),
(1041, 'Aspinal of London', 'femme', 'sacs'),
(1042, 'Anya Hindmarch', 'femme', 'sacs'),
(1043, 'Lulu Guinness', 'femme', 'sacs'),
(1044, 'Danse Lente', 'femme', 'sacs'),
(1045, 'Little Liffner', 'femme', 'sacs'),
(1046, 'Savette', 'femme', 'sacs'),
(1047, 'Christian Louboutin', 'femme', 'chaussures'),
(1048, 'Manolo Blahnik', 'femme', 'chaussures'),
(1049, 'Jimmy Choo', 'femme', 'chaussures'),
(1050, 'Gianvito Rossi', 'femme', 'chaussures'),
(1051, 'Stuart Weitzman', 'femme', 'chaussures'),
(1052, 'Roger Vivier', 'femme', 'chaussures'),
(1053, 'Aquazzura', 'femme', 'chaussures'),
(1054, 'The Row', 'femme', 'chaussures'),
(1055, 'Golden Goose', 'femme', 'chaussures'),
(1056, 'Giuseppe Zanotti', 'femme', 'chaussures'),
(1057, 'Sergio Rossi', 'femme', 'chaussures'),
(1058, 'René Caovilla', 'femme', 'chaussures'),
(1059, 'Charlotte Olympia', 'femme', 'chaussures'),
(1060, 'Sophia Webster', 'femme', 'chaussures'),
(1061, 'Casadei', 'femme', 'chaussures'),
(1062, 'Le Silla', 'femme', 'chaussures'),
(1063, 'Malone Souliers', 'femme', 'chaussures'),
(1064, 'Alexandre Birman', 'femme', 'chaussures'),
(1065, 'Alias Mae', 'femme', 'chaussures'),
(1066, 'Tony Bianco', 'femme', 'chaussures'),
(1067, 'Aje', 'femme', 'chaussures'),
(1068, 'Schutz', 'femme', 'chaussures'),
(1069, 'Veronica Beard', 'femme', 'chaussures'),
(1070, 'Paris Texas', 'femme', 'chaussures'),
(1071, 'Boyy', 'femme', 'chaussures'),
(1072, 'APL', 'femme', 'chaussures'),
(1073, 'Sam Edelman', 'femme', 'chaussures'),
(1074, 'Van Cleef & Arpels', 'femme', 'accessoires'),
(1075, 'Tiffany & Co.', 'femme', 'accessoires'),
(1076, 'Bulgari', 'femme', 'accessoires'),
(1077, 'Pomellato', 'femme', 'accessoires'),
(1078, 'Chopard', 'femme', 'accessoires'),
(1079, 'Messika', 'femme', 'accessoires'),
(1080, 'Piaget', 'femme', 'accessoires'),
(1081, 'Dior Joaillerie', 'femme', 'accessoires'),
(1082, 'Chanel Fine Jewellery', 'femme', 'accessoires'),
(1083, 'Mikimoto', 'femme', 'accessoires'),
(1084, 'Tasaki', 'femme', 'accessoires'),
(1085, 'De Beers', 'femme', 'accessoires'),
(1086, 'Graff', 'femme', 'accessoires'),
(1087, 'Harry Winston', 'femme', 'accessoires'),
(1088, 'Boucheron', 'femme', 'accessoires'),
(1089, 'Mauboussin', 'femme', 'accessoires'),
(1090, 'APM Monaco', 'femme', 'accessoires'),
(1091, 'Agatha', 'femme', 'accessoires'),
(1092, 'Djula', 'femme', 'accessoires'),
(1093, 'Jennifer Meyer', 'femme', 'accessoires'),
(1094, 'Missoma', 'femme', 'accessoires'),
(1095, 'Gorjana', 'femme', 'accessoires'),
(1096, 'Monica Vinader', 'femme', 'accessoires'),
(1097, 'Thomas Sabo', 'femme', 'accessoires'),
(1098, 'Les Néréides', 'femme', 'accessoires'),
(1099, 'Satellite', 'femme', 'accessoires'),
(1100, 'Gas Bijoux', 'femme', 'accessoires'),
(1101, 'Marie Lichtenberg', 'femme', 'accessoires'),
(1102, 'Foundrae', 'femme', 'accessoires'),
(1103, 'Pippa Small', 'femme', 'accessoires'),
(1104, 'Patek Philippe', 'femme', 'accessoires'),
(1105, 'Audemars Piguet', 'femme', 'accessoires'),
(1106, 'Omega', 'femme', 'accessoires'),
(1107, 'TAG Heuer', 'femme', 'accessoires'),
(1108, 'IWC', 'femme', 'accessoires'),
(1109, 'Rolex', 'femme', 'accessoires'),
(1110, 'Lululemon', 'femme', 'vetements'),
(1111, 'Lululemon', 'femme', 'chaussures'),
(1112, 'Alo Yoga', 'femme', 'vetements'),
(1113, 'Alo Yoga', 'femme', 'chaussures'),
(1114, 'Vuori', 'femme', 'vetements'),
(1115, 'Vuori', 'femme', 'chaussures'),
(1116, 'Sweaty Betty', 'femme', 'vetements'),
(1117, 'Sweaty Betty', 'femme', 'chaussures'),
(1118, 'Varley', 'femme', 'vetements'),
(1119, 'Varley', 'femme', 'chaussures'),
(1120, 'Adidas by Stella McCartney', 'femme', 'vetements'),
(1121, 'Adidas by Stella McCartney', 'femme', 'chaussures'),
(1122, 'Nike x sacai', 'femme', 'vetements'),
(1123, 'Nike x sacai', 'femme', 'chaussures'),
(1124, 'Arc''teryx', 'femme', 'vetements'),
(1125, 'Arc''teryx', 'femme', 'chaussures'),
(1126, 'Goldbergh', 'femme', 'vetements'),
(1127, 'Goldbergh', 'femme', 'chaussures'),
(1128, 'Fusalp', 'femme', 'vetements'),
(1129, 'Fusalp', 'femme', 'chaussures'),
(1130, 'Perfect Moment', 'femme', 'vetements'),
(1131, 'Perfect Moment', 'femme', 'chaussures'),
(1132, 'Rossignol', 'femme', 'vetements'),
(1133, 'Rossignol', 'femme', 'chaussures'),
(1134, 'Moncler Grenoble', 'femme', 'vetements'),
(1135, 'Moncler Grenoble', 'femme', 'chaussures'),
(1136, 'Bogner', 'femme', 'vetements'),
(1137, 'Bogner', 'femme', 'chaussures'),
(1138, 'Kjus', 'femme', 'vetements'),
(1139, 'Kjus', 'femme', 'chaussures'),
(1140, 'Descente', 'femme', 'vetements'),
(1141, 'Descente', 'femme', 'chaussures'),
(1142, 'Roxy', 'femme', 'vetements'),
(1143, 'Roxy', 'femme', 'chaussures'),
(1144, 'Billabong', 'femme', 'vetements'),
(1145, 'Billabong', 'femme', 'chaussures'),
(1146, 'Rip Curl', 'femme', 'vetements'),
(1147, 'Rip Curl', 'femme', 'chaussures'),
(1148, 'Giorgio Armani', 'homme', 'vetements'),
(1149, 'Giorgio Armani', 'homme', 'chaussures'),
(1150, 'Giorgio Armani', 'homme', 'sacs'),
(1151, 'Giorgio Armani', 'homme', 'accessoires'),
(1152, 'Emporio Armani', 'homme', 'vetements'),
(1153, 'Emporio Armani', 'homme', 'chaussures'),
(1154, 'Emporio Armani', 'homme', 'sacs'),
(1155, 'Tom Ford', 'homme', 'vetements'),
(1156, 'Tom Ford', 'homme', 'chaussures'),
(1157, 'Tom Ford', 'homme', 'sacs'),
(1158, 'Tom Ford', 'homme', 'accessoires'),
(1159, 'Zegna', 'homme', 'vetements'),
(1160, 'Zegna', 'homme', 'chaussures'),
(1161, 'Zegna', 'homme', 'sacs'),
(1162, 'Zegna', 'homme', 'accessoires'),
(1163, 'Brioni', 'homme', 'vetements'),
(1164, 'Brioni', 'homme', 'chaussures'),
(1165, 'Brioni', 'homme', 'sacs'),
(1166, 'Brioni', 'homme', 'accessoires'),
(1167, 'Berluti', 'homme', 'vetements'),
(1168, 'Berluti', 'homme', 'chaussures'),
(1169, 'Berluti', 'homme', 'sacs'),
(1170, 'Berluti', 'homme', 'accessoires'),
(1171, 'Canali', 'homme', 'vetements'),
(1172, 'Canali', 'homme', 'chaussures'),
(1173, 'Canali', 'homme', 'sacs'),
(1174, 'Canali', 'homme', 'accessoires'),
(1175, 'Kiton', 'homme', 'vetements'),
(1176, 'Kiton', 'homme', 'chaussures'),
(1177, 'Kiton', 'homme', 'sacs'),
(1178, 'Kiton', 'homme', 'accessoires'),
(1179, 'Brunello Cucinelli', 'homme', 'vetements'),
(1180, 'Brunello Cucinelli', 'homme', 'chaussures'),
(1181, 'Brunello Cucinelli', 'homme', 'sacs'),
(1182, 'Brunello Cucinelli', 'homme', 'accessoires'),
(1183, 'Ralph Lauren Purple Label', 'homme', 'vetements'),
(1184, 'Ralph Lauren Purple Label', 'homme', 'chaussures'),
(1185, 'Ralph Lauren Purple Label', 'homme', 'sacs'),
(1186, 'Ralph Lauren Purple Label', 'homme', 'accessoires'),
(1187, 'Loro Piana', 'homme', 'vetements'),
(1188, 'Loro Piana', 'homme', 'chaussures'),
(1189, 'Loro Piana', 'homme', 'sacs'),
(1190, 'Loro Piana', 'homme', 'accessoires'),
(1191, 'Thom Browne', 'homme', 'vetements'),
(1192, 'Thom Browne', 'homme', 'chaussures'),
(1193, 'Thom Browne', 'homme', 'sacs'),
(1194, 'Thom Browne', 'homme', 'accessoires'),
(1195, 'Stone Island', 'homme', 'chaussures'),
(1196, 'Stone Island', 'homme', 'sacs'),
(1197, 'Stone Island', 'homme', 'accessoires'),
(1198, 'C.P. Company', 'homme', 'vetements'),
(1199, 'C.P. Company', 'homme', 'chaussures'),
(1200, 'C.P. Company', 'homme', 'sacs'),
(1201, 'C.P. Company', 'homme', 'accessoires'),
(1202, 'Ami Paris', 'homme', 'vetements'),
(1203, 'Ami Paris', 'homme', 'chaussures'),
(1204, 'Ami Paris', 'homme', 'sacs'),
(1205, 'Ami Paris', 'homme', 'accessoires'),
(1206, 'Moncler', 'homme', 'chaussures'),
(1207, 'Moncler', 'homme', 'sacs'),
(1208, 'Canada Goose', 'homme', 'vetements'),
(1209, 'Canada Goose', 'homme', 'chaussures'),
(1210, 'Canada Goose', 'homme', 'sacs'),
(1211, 'Canada Goose', 'homme', 'accessoires'),
(1212, 'Dsquared2', 'homme', 'vetements'),
(1213, 'Dsquared2', 'homme', 'chaussures'),
(1214, 'Dsquared2', 'homme', 'sacs'),
(1215, 'Dsquared2', 'homme', 'accessoires'),
(1216, 'Dolce & Gabbana', 'homme', 'vetements'),
(1217, 'Dolce & Gabbana', 'homme', 'chaussures'),
(1218, 'Dolce & Gabbana', 'homme', 'sacs'),
(1219, 'Versace', 'homme', 'chaussures'),
(1220, 'Versace', 'homme', 'sacs'),
(1221, 'Prada', 'homme', 'sacs'),
(1222, 'Gucci', 'homme', 'sacs'),
(1223, 'Fendi', 'homme', 'vetements'),
(1224, 'Fendi', 'homme', 'chaussures'),
(1225, 'Fendi', 'homme', 'sacs'),
(1226, 'Fendi', 'homme', 'accessoires'),
(1227, 'Givenchy', 'homme', 'chaussures'),
(1228, 'Givenchy', 'homme', 'sacs'),
(1229, 'Givenchy', 'homme', 'accessoires'),
(1230, 'Dior Homme', 'homme', 'vetements'),
(1231, 'Dior Homme', 'homme', 'chaussures'),
(1232, 'Dior Homme', 'homme', 'sacs'),
(1233, 'Dior Homme', 'homme', 'accessoires'),
(1234, 'Saint Laurent', 'homme', 'chaussures'),
(1235, 'Saint Laurent', 'homme', 'sacs'),
(1236, 'Balenciaga', 'homme', 'chaussures'),
(1237, 'Balenciaga', 'homme', 'sacs'),
(1238, 'Off-White', 'homme', 'vetements'),
(1239, 'Off-White', 'homme', 'chaussures'),
(1240, 'Off-White', 'homme', 'sacs'),
(1241, 'Off-White', 'homme', 'accessoires'),
(1242, 'Kenzo', 'homme', 'vetements'),
(1243, 'Kenzo', 'homme', 'chaussures'),
(1244, 'Kenzo', 'homme', 'sacs'),
(1245, 'Kenzo', 'homme', 'accessoires'),
(1246, 'Paul Smith', 'homme', 'vetements'),
(1247, 'Paul Smith', 'homme', 'chaussures'),
(1248, 'Paul Smith', 'homme', 'sacs'),
(1249, 'Paul Smith', 'homme', 'accessoires'),
(1250, 'Ted Baker', 'homme', 'vetements'),
(1251, 'Ted Baker', 'homme', 'chaussures'),
(1252, 'Ted Baker', 'homme', 'sacs'),
(1253, 'Ted Baker', 'homme', 'accessoires'),
(1254, 'Hugo Boss', 'homme', 'chaussures'),
(1255, 'Hugo Boss', 'homme', 'sacs'),
(1256, 'Corneliani', 'homme', 'vetements'),
(1257, 'Corneliani', 'homme', 'chaussures'),
(1258, 'Corneliani', 'homme', 'sacs'),
(1259, 'Corneliani', 'homme', 'accessoires'),
(1260, 'Pal Zileri', 'homme', 'vetements'),
(1261, 'Pal Zileri', 'homme', 'chaussures'),
(1262, 'Pal Zileri', 'homme', 'sacs'),
(1263, 'Pal Zileri', 'homme', 'accessoires'),
(1264, 'Boglioli', 'homme', 'vetements'),
(1265, 'Boglioli', 'homme', 'chaussures'),
(1266, 'Boglioli', 'homme', 'sacs'),
(1267, 'Boglioli', 'homme', 'accessoires'),
(1268, 'Herno', 'homme', 'vetements'),
(1269, 'Herno', 'homme', 'chaussures'),
(1270, 'Herno', 'homme', 'sacs'),
(1271, 'Herno', 'homme', 'accessoires'),
(1272, 'Colmar', 'homme', 'vetements'),
(1273, 'Colmar', 'homme', 'chaussures'),
(1274, 'Colmar', 'homme', 'sacs'),
(1275, 'Colmar', 'homme', 'accessoires'),
(1276, 'Woolrich', 'homme', 'vetements'),
(1277, 'Woolrich', 'homme', 'chaussures'),
(1278, 'Woolrich', 'homme', 'sacs'),
(1279, 'Woolrich', 'homme', 'accessoires'),
(1280, 'Belstaff', 'homme', 'vetements'),
(1281, 'Belstaff', 'homme', 'chaussures'),
(1282, 'Belstaff', 'homme', 'sacs'),
(1283, 'Belstaff', 'homme', 'accessoires'),
(1284, 'Barbour', 'homme', 'vetements'),
(1285, 'Barbour', 'homme', 'chaussures'),
(1286, 'Barbour', 'homme', 'sacs'),
(1287, 'Barbour', 'homme', 'accessoires'),
(1288, 'Hackett', 'homme', 'vetements'),
(1289, 'Hackett', 'homme', 'chaussures'),
(1290, 'Hackett', 'homme', 'sacs'),
(1291, 'Hackett', 'homme', 'accessoires'),
(1292, 'Turnbull & Asser', 'homme', 'vetements'),
(1293, 'Turnbull & Asser', 'homme', 'chaussures'),
(1294, 'Turnbull & Asser', 'homme', 'sacs'),
(1295, 'Turnbull & Asser', 'homme', 'accessoires'),
(1296, 'Orlebar Brown', 'homme', 'vetements'),
(1297, 'Orlebar Brown', 'homme', 'chaussures'),
(1298, 'Orlebar Brown', 'homme', 'sacs'),
(1299, 'Orlebar Brown', 'homme', 'accessoires'),
(1300, 'Vilebrequin', 'homme', 'vetements'),
(1301, 'Vilebrequin', 'homme', 'chaussures'),
(1302, 'Vilebrequin', 'homme', 'sacs'),
(1303, 'Vilebrequin', 'homme', 'accessoires'),
(1304, 'Frescobol Carioca', 'homme', 'vetements'),
(1305, 'Frescobol Carioca', 'homme', 'chaussures'),
(1306, 'Frescobol Carioca', 'homme', 'sacs'),
(1307, 'Frescobol Carioca', 'homme', 'accessoires'),
(1308, 'A.P.C.', 'homme', 'chaussures'),
(1309, 'A.P.C.', 'homme', 'sacs'),
(1310, 'Acne Studios', 'homme', 'vetements'),
(1311, 'Acne Studios', 'homme', 'chaussures'),
(1312, 'Acne Studios', 'homme', 'sacs'),
(1313, 'Acne Studios', 'homme', 'accessoires'),
(1314, 'COS', 'homme', 'chaussures'),
(1315, 'COS', 'homme', 'sacs'),
(1316, 'COS', 'homme', 'accessoires'),
(1317, 'Norse Projects', 'homme', 'vetements'),
(1318, 'Norse Projects', 'homme', 'chaussures'),
(1319, 'Norse Projects', 'homme', 'sacs'),
(1320, 'Norse Projects', 'homme', 'accessoires'),
(1321, 'Our Legacy', 'homme', 'vetements'),
(1322, 'Our Legacy', 'homme', 'chaussures'),
(1323, 'Our Legacy', 'homme', 'sacs'),
(1324, 'Our Legacy', 'homme', 'accessoires'),
(1325, 'Carhartt WIP', 'homme', 'vetements'),
(1326, 'Carhartt WIP', 'homme', 'chaussures'),
(1327, 'Carhartt WIP', 'homme', 'sacs'),
(1328, 'Carhartt WIP', 'homme', 'accessoires'),
(1329, 'Margaret Howell', 'homme', 'vetements'),
(1330, 'Margaret Howell', 'homme', 'chaussures'),
(1331, 'Margaret Howell', 'homme', 'sacs'),
(1332, 'Margaret Howell', 'homme', 'accessoires'),
(1333, 'Sunspel', 'homme', 'vetements'),
(1334, 'Sunspel', 'homme', 'chaussures'),
(1335, 'Sunspel', 'homme', 'sacs'),
(1336, 'Sunspel', 'homme', 'accessoires'),
(1337, 'Derek Rose', 'homme', 'vetements'),
(1338, 'Derek Rose', 'homme', 'chaussures'),
(1339, 'Derek Rose', 'homme', 'sacs'),
(1340, 'Derek Rose', 'homme', 'accessoires'),
(1341, 'Calvin Klein', 'homme', 'sacs'),
(1342, 'Tommy Hilfiger', 'homme', 'sacs'),
(1343, 'Lacoste', 'homme', 'sacs'),
(1344, 'Fred Perry', 'homme', 'vetements'),
(1345, 'Fred Perry', 'homme', 'chaussures'),
(1346, 'Fred Perry', 'homme', 'sacs'),
(1347, 'Fred Perry', 'homme', 'accessoires'),
(1348, 'Polo Ralph Lauren', 'homme', 'vetements'),
(1349, 'Polo Ralph Lauren', 'homme', 'chaussures'),
(1350, 'Polo Ralph Lauren', 'homme', 'sacs'),
(1351, 'Polo Ralph Lauren', 'homme', 'accessoires'),
(1352, 'Brooks Brothers', 'homme', 'vetements'),
(1353, 'Brooks Brothers', 'homme', 'chaussures'),
(1354, 'Brooks Brothers', 'homme', 'sacs'),
(1355, 'Brooks Brothers', 'homme', 'accessoires'),
(1356, 'Todd Snyder', 'homme', 'vetements'),
(1357, 'Todd Snyder', 'homme', 'chaussures'),
(1358, 'Todd Snyder', 'homme', 'sacs'),
(1359, 'Todd Snyder', 'homme', 'accessoires'),
(1360, 'Faherty', 'homme', 'vetements'),
(1361, 'Faherty', 'homme', 'chaussures'),
(1362, 'Faherty', 'homme', 'sacs'),
(1363, 'Faherty', 'homme', 'accessoires'),
(1364, 'Reigning Champ', 'homme', 'vetements'),
(1365, 'Reigning Champ', 'homme', 'chaussures'),
(1366, 'Reigning Champ', 'homme', 'sacs'),
(1367, 'Reigning Champ', 'homme', 'accessoires'),
(1368, 'Lardini', 'homme', 'vetements'),
(1369, 'Lardini', 'homme', 'chaussures'),
(1370, 'Lardini', 'homme', 'sacs'),
(1371, 'Lardini', 'homme', 'accessoires'),
(1372, 'Sartorio Napoli', 'homme', 'vetements'),
(1373, 'Sartorio Napoli', 'homme', 'chaussures'),
(1374, 'Sartorio Napoli', 'homme', 'sacs'),
(1375, 'Sartorio Napoli', 'homme', 'accessoires'),
(1376, 'Cesare Attolini', 'homme', 'vetements'),
(1377, 'Cesare Attolini', 'homme', 'chaussures'),
(1378, 'Cesare Attolini', 'homme', 'sacs'),
(1379, 'Cesare Attolini', 'homme', 'accessoires'),
(1380, 'Isaia', 'homme', 'vetements'),
(1381, 'Isaia', 'homme', 'chaussures'),
(1382, 'Isaia', 'homme', 'sacs'),
(1383, 'Isaia', 'homme', 'accessoires'),
(1384, 'Luigi Borrelli', 'homme', 'vetements'),
(1385, 'Luigi Borrelli', 'homme', 'chaussures'),
(1386, 'Luigi Borrelli', 'homme', 'sacs'),
(1387, 'Luigi Borrelli', 'homme', 'accessoires'),
(1388, 'Belvest', 'homme', 'vetements'),
(1389, 'Belvest', 'homme', 'chaussures'),
(1390, 'Belvest', 'homme', 'sacs'),
(1391, 'Belvest', 'homme', 'accessoires'),
(1392, 'Caruso', 'homme', 'vetements'),
(1393, 'Caruso', 'homme', 'chaussures'),
(1394, 'Caruso', 'homme', 'sacs'),
(1395, 'Caruso', 'homme', 'accessoires'),
(1396, 'Lubiam', 'homme', 'vetements'),
(1397, 'Lubiam', 'homme', 'chaussures'),
(1398, 'Lubiam', 'homme', 'sacs'),
(1399, 'Lubiam', 'homme', 'accessoires'),
(1400, 'Chester Barrie', 'homme', 'vetements'),
(1401, 'Chester Barrie', 'homme', 'chaussures'),
(1402, 'Chester Barrie', 'homme', 'sacs'),
(1403, 'Chester Barrie', 'homme', 'accessoires'),
(1404, 'Richard James', 'homme', 'vetements'),
(1405, 'Richard James', 'homme', 'chaussures'),
(1406, 'Richard James', 'homme', 'sacs'),
(1407, 'Richard James', 'homme', 'accessoires'),
(1408, 'Henry Poole', 'homme', 'vetements'),
(1409, 'Henry Poole', 'homme', 'chaussures'),
(1410, 'Henry Poole', 'homme', 'sacs'),
(1411, 'Henry Poole', 'homme', 'accessoires'),
(1412, 'Norton & Sons', 'homme', 'vetements'),
(1413, 'Norton & Sons', 'homme', 'chaussures'),
(1414, 'Norton & Sons', 'homme', 'sacs'),
(1415, 'Norton & Sons', 'homme', 'accessoires'),
(1416, 'Huntsman', 'homme', 'vetements'),
(1417, 'Huntsman', 'homme', 'chaussures'),
(1418, 'Huntsman', 'homme', 'sacs'),
(1419, 'Huntsman', 'homme', 'accessoires'),
(1420, 'Anderson & Sheppard', 'homme', 'vetements'),
(1421, 'Anderson & Sheppard', 'homme', 'chaussures'),
(1422, 'Anderson & Sheppard', 'homme', 'sacs'),
(1423, 'Anderson & Sheppard', 'homme', 'accessoires'),
(1424, 'Gieves & Hawkes', 'homme', 'vetements'),
(1425, 'Gieves & Hawkes', 'homme', 'chaussures'),
(1426, 'Gieves & Hawkes', 'homme', 'sacs'),
(1427, 'Gieves & Hawkes', 'homme', 'accessoires'),
(1428, 'Dege & Skinner', 'homme', 'vetements'),
(1429, 'Dege & Skinner', 'homme', 'chaussures'),
(1430, 'Dege & Skinner', 'homme', 'sacs'),
(1431, 'Dege & Skinner', 'homme', 'accessoires'),
(1432, 'Ozwald Boateng', 'homme', 'vetements'),
(1433, 'Ozwald Boateng', 'homme', 'chaussures'),
(1434, 'Ozwald Boateng', 'homme', 'sacs'),
(1435, 'Ozwald Boateng', 'homme', 'accessoires'),
(1436, 'Tiger of Sweden', 'homme', 'vetements'),
(1437, 'Tiger of Sweden', 'homme', 'chaussures'),
(1438, 'Tiger of Sweden', 'homme', 'sacs'),
(1439, 'Tiger of Sweden', 'homme', 'accessoires'),
(1440, 'Simon Carter', 'homme', 'vetements'),
(1441, 'Simon Carter', 'homme', 'chaussures'),
(1442, 'Simon Carter', 'homme', 'sacs'),
(1443, 'Simon Carter', 'homme', 'accessoires'),
(1444, 'Reiss', 'homme', 'vetements'),
(1445, 'Reiss', 'homme', 'chaussures'),
(1446, 'Reiss', 'homme', 'sacs'),
(1447, 'Reiss', 'homme', 'accessoires'),
(1448, 'Suitsupply', 'homme', 'vetements'),
(1449, 'Suitsupply', 'homme', 'chaussures'),
(1450, 'Suitsupply', 'homme', 'sacs'),
(1451, 'Suitsupply', 'homme', 'accessoires'),
(1452, 'John Lobb', 'homme', 'chaussures'),
(1453, 'Edward Green', 'homme', 'chaussures'),
(1454, 'Church''s', 'homme', 'chaussures'),
(1455, 'Santoni', 'homme', 'chaussures'),
(1456, 'Common Projects', 'homme', 'chaussures'),
(1457, 'Golden Goose', 'homme', 'chaussures'),
(1458, 'Axel Arigato', 'homme', 'chaussures'),
(1459, 'Filling Pieces', 'homme', 'chaussures'),
(1460, 'Veja', 'homme', 'chaussures'),
(1461, 'Tod''s', 'homme', 'chaussures'),
(1462, 'Mephisto', 'homme', 'chaussures'),
(1463, 'Paraboot', 'homme', 'chaussures'),
(1464, 'Tricker''s', 'homme', 'chaussures'),
(1465, 'Grenson', 'homme', 'chaussures'),
(1466, 'Loake', 'homme', 'chaussures'),
(1467, 'Crockett & Jones', 'homme', 'chaussures'),
(1468, 'Alfred Sargent', 'homme', 'chaussures'),
(1469, 'Barker', 'homme', 'chaussures'),
(1470, 'Magnanni', 'homme', 'chaussures'),
(1471, 'Carmina', 'homme', 'chaussures'),
(1472, 'Meermin', 'homme', 'chaussures'),
(1473, 'Viberg', 'homme', 'chaussures'),
(1474, 'Red Wing Heritage', 'homme', 'chaussures'),
(1475, 'Alden', 'homme', 'chaussures'),
(1476, 'Thursday Boot', 'homme', 'chaussures'),
(1477, 'Oliver Cabell', 'homme', 'chaussures'),
(1478, 'Grant Stone', 'homme', 'chaussures'),
(1479, 'Beckett Simonon', 'homme', 'chaussures'),
(1480, 'Nike Air Force 1', 'homme', 'chaussures'),
(1481, 'Nike Air Max', 'homme', 'chaussures'),
(1482, 'Adidas Samba', 'homme', 'chaussures'),
(1483, 'Adidas Stan Smith', 'homme', 'chaussures'),
(1484, 'New Balance 550', 'homme', 'chaussures'),
(1485, 'New Balance 990', 'homme', 'chaussures'),
(1486, 'New Balance 574', 'homme', 'chaussures'),
(1487, 'Asics Gel-Kayano', 'homme', 'chaussures'),
(1488, 'Asics Gel-Lyte', 'homme', 'chaussures'),
(1489, 'Converse Chuck Taylor', 'homme', 'chaussures'),
(1490, 'Rolex', 'homme', 'accessoires'),
(1491, 'Patek Philippe', 'homme', 'accessoires'),
(1492, 'Audemars Piguet', 'homme', 'accessoires'),
(1493, 'IWC', 'homme', 'accessoires'),
(1494, 'Breitling', 'homme', 'accessoires'),
(1495, 'Omega', 'homme', 'accessoires'),
(1496, 'TAG Heuer', 'homme', 'accessoires'),
(1497, 'Hublot', 'homme', 'accessoires'),
(1498, 'Richard Mille', 'homme', 'accessoires'),
(1499, 'Zenith', 'homme', 'accessoires'),
(1500, 'Jaeger-LeCoultre', 'homme', 'accessoires'),
(1501, 'A. Lange & Söhne', 'homme', 'accessoires'),
(1502, 'Vacheron Constantin', 'homme', 'accessoires'),
(1503, 'Blancpain', 'homme', 'accessoires'),
(1504, 'Chopard', 'homme', 'accessoires'),
(1505, 'Panerai', 'homme', 'accessoires'),
(1506, 'Bell & Ross', 'homme', 'accessoires'),
(1507, 'Oris', 'homme', 'accessoires'),
(1508, 'Longines', 'homme', 'accessoires'),
(1509, 'Tudor', 'homme', 'accessoires'),
(1510, 'Nomos', 'homme', 'accessoires'),
(1511, 'Sinn', 'homme', 'accessoires'),
(1512, 'Grand Seiko', 'homme', 'accessoires'),
(1513, 'Seiko Presage', 'homme', 'accessoires'),
(1514, 'Citizen', 'homme', 'accessoires'),
(1515, 'Hamilton', 'homme', 'accessoires'),
(1516, 'Frederique Constant', 'homme', 'accessoires'),
(1517, 'Maurice Lacroix', 'homme', 'accessoires'),
(1518, 'Raymond Weil', 'homme', 'accessoires'),
(1519, 'Baume & Mercier', 'homme', 'accessoires'),
(1520, 'Mido', 'homme', 'accessoires'),
(1521, 'Alpina', 'homme', 'accessoires'),
(1522, 'Certina', 'homme', 'accessoires'),
(1523, 'Rado', 'homme', 'accessoires'),
(1524, 'Bulova', 'homme', 'accessoires'),
(1525, 'Seiko', 'homme', 'accessoires'),
(1526, 'Casio G-Shock', 'homme', 'accessoires'),
(1527, 'Casio Edifice', 'homme', 'accessoires'),
(1528, 'Montblanc', 'homme', 'accessoires'),
(1529, 'Dunhill', 'homme', 'accessoires'),
(1530, 'Smythson', 'homme', 'accessoires'),
(1531, 'Ettinger', 'homme', 'accessoires'),
(1532, 'Piquadro', 'homme', 'accessoires'),
(1533, 'Ganzo', 'homme', 'accessoires'),
(1534, 'S.T. Dupont', 'homme', 'accessoires'),
(1535, 'Hermès', 'homme', 'sacs'),
(1536, 'Louis Vuitton', 'homme', 'sacs'),
(1537, 'Mismo', 'homme', 'sacs'),
(1538, 'Bennett Winch', 'homme', 'sacs'),
(1539, 'Globe-Trotter', 'homme', 'sacs'),
(1540, 'Rimowa', 'homme', 'sacs'),
(1541, 'Tumi', 'homme', 'sacs'),
(1542, 'Samsonite', 'homme', 'sacs'),
(1543, 'Briggs & Riley', 'homme', 'sacs'),
(1544, 'Porsche Design', 'homme', 'sacs'),
(1545, 'Arc''teryx', 'homme', 'vetements'),
(1546, 'Arc''teryx', 'homme', 'chaussures'),
(1547, 'Patagonia', 'homme', 'vetements'),
(1548, 'Patagonia', 'homme', 'chaussures'),
(1549, 'The North Face', 'homme', 'chaussures'),
(1550, 'Mammut', 'homme', 'vetements'),
(1551, 'Mammut', 'homme', 'chaussures'),
(1552, 'Salewa', 'homme', 'vetements'),
(1553, 'Salewa', 'homme', 'chaussures'),
(1554, 'Kjus', 'homme', 'vetements'),
(1555, 'Kjus', 'homme', 'chaussures'),
(1556, 'Bogner', 'homme', 'vetements'),
(1557, 'Bogner', 'homme', 'chaussures'),
(1558, 'Fusalp', 'homme', 'vetements'),
(1559, 'Fusalp', 'homme', 'chaussures'),
(1560, 'Perfect Moment', 'homme', 'vetements'),
(1561, 'Perfect Moment', 'homme', 'chaussures'),
(1562, 'Goldbergh', 'homme', 'vetements'),
(1563, 'Goldbergh', 'homme', 'chaussures'),
(1564, 'Descente', 'homme', 'vetements'),
(1565, 'Descente', 'homme', 'chaussures'),
(1566, 'Moncler Grenoble', 'homme', 'vetements'),
(1567, 'Moncler Grenoble', 'homme', 'chaussures'),
(1568, 'Moose Knuckles', 'homme', 'vetements'),
(1569, 'Moose Knuckles', 'homme', 'chaussures'),
(1570, 'Nobis', 'homme', 'vetements'),
(1571, 'Nobis', 'homme', 'chaussures'),
(1572, 'Mackage', 'homme', 'vetements'),
(1573, 'Mackage', 'homme', 'chaussures'),
(1574, 'On Running', 'homme', 'vetements'),
(1575, 'On Running', 'homme', 'chaussures'),
(1576, 'Hoka', 'homme', 'vetements'),
(1577, 'Hoka', 'homme', 'chaussures'),
(1578, 'Salomon', 'homme', 'vetements'),
(1579, 'Asics', 'homme', 'vetements'),
(1580, 'Under Armour', 'homme', 'chaussures'),
(1581, 'Lululemon Men', 'homme', 'vetements'),
(1582, 'Lululemon Men', 'homme', 'chaussures'),
(1583, 'Vuori', 'homme', 'vetements'),
(1584, 'Vuori', 'homme', 'chaussures'),
(1585, 'Caramel Baby & Child', 'enfant', 'vetements'),
(1586, 'Caramel Baby & Child', 'enfant', 'chaussures'),
(1587, 'Caramel Baby & Child', 'enfant', 'sacs'),
(1588, 'Caramel Baby & Child', 'enfant', 'accessoires'),
(1589, 'Burberry Kids', 'enfant', 'vetements'),
(1590, 'Burberry Kids', 'enfant', 'chaussures'),
(1591, 'Burberry Kids', 'enfant', 'sacs'),
(1592, 'Burberry Kids', 'enfant', 'accessoires'),
(1593, 'Little Marc Jacobs', 'enfant', 'vetements'),
(1594, 'Little Marc Jacobs', 'enfant', 'chaussures'),
(1595, 'Little Marc Jacobs', 'enfant', 'sacs'),
(1596, 'Little Marc Jacobs', 'enfant', 'accessoires'),
(1597, 'Versace Kids', 'enfant', 'vetements'),
(1598, 'Versace Kids', 'enfant', 'chaussures'),
(1599, 'Versace Kids', 'enfant', 'sacs'),
(1600, 'Versace Kids', 'enfant', 'accessoires'),
(1601, 'Dior Baby', 'enfant', 'vetements'),
(1602, 'Dior Baby', 'enfant', 'chaussures'),
(1603, 'Dior Baby', 'enfant', 'sacs'),
(1604, 'Dior Baby', 'enfant', 'accessoires'),
(1605, 'Il Gufo', 'enfant', 'vetements'),
(1606, 'Il Gufo', 'enfant', 'chaussures'),
(1607, 'Il Gufo', 'enfant', 'sacs'),
(1608, 'Il Gufo', 'enfant', 'accessoires'),
(1609, 'Molo', 'enfant', 'vetements'),
(1610, 'Molo', 'enfant', 'chaussures'),
(1611, 'Molo', 'enfant', 'sacs'),
(1612, 'Molo', 'enfant', 'accessoires'),
(1613, 'Jottum', 'enfant', 'vetements'),
(1614, 'Jottum', 'enfant', 'chaussures'),
(1615, 'Jottum', 'enfant', 'sacs'),
(1616, 'Jottum', 'enfant', 'accessoires'),
(1617, 'Confetti', 'enfant', 'vetements'),
(1618, 'Confetti', 'enfant', 'chaussures'),
(1619, 'Confetti', 'enfant', 'sacs'),
(1620, 'Confetti', 'enfant', 'accessoires'),
(1621, 'Marèse', 'enfant', 'vetements'),
(1622, 'Marèse', 'enfant', 'chaussures'),
(1623, 'Marèse', 'enfant', 'sacs'),
(1624, 'Marèse', 'enfant', 'accessoires'),
(1625, 'Angel & Rocket', 'enfant', 'vetements'),
(1626, 'Angel & Rocket', 'enfant', 'chaussures'),
(1627, 'Angel & Rocket', 'enfant', 'sacs'),
(1628, 'Angel & Rocket', 'enfant', 'accessoires'),
(1629, 'Neck & Neck', 'enfant', 'vetements'),
(1630, 'Neck & Neck', 'enfant', 'chaussures'),
(1631, 'Neck & Neck', 'enfant', 'sacs'),
(1632, 'Neck & Neck', 'enfant', 'accessoires'),
(1633, 'Tutto Piccolo', 'enfant', 'vetements'),
(1634, 'Tutto Piccolo', 'enfant', 'chaussures'),
(1635, 'Tutto Piccolo', 'enfant', 'sacs'),
(1636, 'Tutto Piccolo', 'enfant', 'accessoires'),
(1637, 'Paz Rodriguez', 'enfant', 'vetements'),
(1638, 'Paz Rodriguez', 'enfant', 'chaussures'),
(1639, 'Paz Rodriguez', 'enfant', 'sacs'),
(1640, 'Paz Rodriguez', 'enfant', 'accessoires'),
(1641, 'Laranjinha', 'enfant', 'vetements'),
(1642, 'Laranjinha', 'enfant', 'chaussures'),
(1643, 'Laranjinha', 'enfant', 'sacs'),
(1644, 'Laranjinha', 'enfant', 'accessoires'),
(1645, 'Aletta', 'enfant', 'vetements'),
(1646, 'Aletta', 'enfant', 'chaussures'),
(1647, 'Aletta', 'enfant', 'sacs'),
(1648, 'Aletta', 'enfant', 'accessoires'),
(1649, 'Charabia', 'enfant', 'vetements'),
(1650, 'Charabia', 'enfant', 'chaussures'),
(1651, 'Charabia', 'enfant', 'sacs'),
(1652, 'Charabia', 'enfant', 'accessoires'),
(1653, 'Louis Louise', 'enfant', 'vetements'),
(1654, 'Louis Louise', 'enfant', 'chaussures'),
(1655, 'Louis Louise', 'enfant', 'sacs'),
(1656, 'Louis Louise', 'enfant', 'accessoires'),
(1657, 'Paade Mode', 'enfant', 'vetements'),
(1658, 'Paade Mode', 'enfant', 'chaussures'),
(1659, 'Paade Mode', 'enfant', 'sacs'),
(1660, 'Paade Mode', 'enfant', 'accessoires'),
(1661, 'Liewood', 'enfant', 'vetements'),
(1662, 'Liewood', 'enfant', 'chaussures'),
(1663, 'Liewood', 'enfant', 'sacs'),
(1664, 'Liewood', 'enfant', 'accessoires'),
(1665, 'Konges Sløjd', 'enfant', 'vetements'),
(1666, 'Konges Sløjd', 'enfant', 'chaussures'),
(1667, 'Konges Sløjd', 'enfant', 'sacs'),
(1668, 'Konges Sløjd', 'enfant', 'accessoires'),
(1669, 'Cam Cam Copenhagen', 'enfant', 'vetements'),
(1670, 'Cam Cam Copenhagen', 'enfant', 'chaussures'),
(1671, 'Cam Cam Copenhagen', 'enfant', 'sacs'),
(1672, 'Cam Cam Copenhagen', 'enfant', 'accessoires'),
(1673, 'Ferm Living Kids', 'enfant', 'vetements'),
(1674, 'Ferm Living Kids', 'enfant', 'chaussures'),
(1675, 'Ferm Living Kids', 'enfant', 'sacs'),
(1676, 'Ferm Living Kids', 'enfant', 'accessoires'),
(1677, 'Little Dutch', 'enfant', 'vetements'),
(1678, 'Little Dutch', 'enfant', 'chaussures'),
(1679, 'Little Dutch', 'enfant', 'sacs'),
(1680, 'Little Dutch', 'enfant', 'accessoires'),
(1681, 'Noralee', 'enfant', 'vetements'),
(1682, 'Noralee', 'enfant', 'chaussures'),
(1683, 'Noralee', 'enfant', 'sacs'),
(1684, 'Noralee', 'enfant', 'accessoires'),
(1685, 'Rylee + Cru', 'enfant', 'vetements'),
(1686, 'Rylee + Cru', 'enfant', 'chaussures'),
(1687, 'Rylee + Cru', 'enfant', 'sacs'),
(1688, 'Rylee + Cru', 'enfant', 'accessoires'),
(1689, 'Petite Lucette', 'enfant', 'vetements'),
(1690, 'Petite Lucette', 'enfant', 'chaussures'),
(1691, 'Petite Lucette', 'enfant', 'sacs'),
(1692, 'Petite Lucette', 'enfant', 'accessoires'),
(1693, 'Les Petites Choses', 'enfant', 'vetements'),
(1694, 'Les Petites Choses', 'enfant', 'chaussures'),
(1695, 'Les Petites Choses', 'enfant', 'sacs'),
(1696, 'Les Petites Choses', 'enfant', 'accessoires'),
(1697, 'Louise Misha', 'enfant', 'vetements'),
(1698, 'Louise Misha', 'enfant', 'chaussures'),
(1699, 'Louise Misha', 'enfant', 'sacs'),
(1700, 'Louise Misha', 'enfant', 'accessoires'),
(1701, 'Stone Island Junior', 'enfant', 'vetements'),
(1702, 'Stone Island Junior', 'enfant', 'chaussures'),
(1703, 'Stone Island Junior', 'enfant', 'sacs'),
(1704, 'Stone Island Junior', 'enfant', 'accessoires'),
(1705, 'C.P. Company Kids', 'enfant', 'vetements'),
(1706, 'C.P. Company Kids', 'enfant', 'chaussures'),
(1707, 'C.P. Company Kids', 'enfant', 'sacs'),
(1708, 'C.P. Company Kids', 'enfant', 'accessoires'),
(1709, 'Dsquared2 Kids', 'enfant', 'vetements'),
(1710, 'Dsquared2 Kids', 'enfant', 'chaussures'),
(1711, 'Dsquared2 Kids', 'enfant', 'sacs'),
(1712, 'Dsquared2 Kids', 'enfant', 'accessoires'),
(1713, 'Timberland Kids', 'enfant', 'vetements'),
(1714, 'Timberland Kids', 'enfant', 'chaussures'),
(1715, 'Timberland Kids', 'enfant', 'sacs'),
(1716, 'Timberland Kids', 'enfant', 'accessoires'),
(1717, 'Tommy Hilfiger Kids', 'enfant', 'vetements'),
(1718, 'Tommy Hilfiger Kids', 'enfant', 'chaussures'),
(1719, 'Tommy Hilfiger Kids', 'enfant', 'sacs'),
(1720, 'Tommy Hilfiger Kids', 'enfant', 'accessoires'),
(1721, 'Lacoste Kids', 'enfant', 'vetements'),
(1722, 'Lacoste Kids', 'enfant', 'chaussures'),
(1723, 'Lacoste Kids', 'enfant', 'sacs'),
(1724, 'Lacoste Kids', 'enfant', 'accessoires'),
(1725, 'Polo Ralph Lauren Boys', 'enfant', 'vetements'),
(1726, 'Polo Ralph Lauren Boys', 'enfant', 'chaussures'),
(1727, 'Polo Ralph Lauren Boys', 'enfant', 'sacs'),
(1728, 'Polo Ralph Lauren Boys', 'enfant', 'accessoires'),
(1729, 'Pepe Jeans Kids', 'enfant', 'vetements'),
(1730, 'Pepe Jeans Kids', 'enfant', 'chaussures'),
(1731, 'Pepe Jeans Kids', 'enfant', 'sacs'),
(1732, 'Pepe Jeans Kids', 'enfant', 'accessoires'),
(1733, 'Scotch Shrunk', 'enfant', 'vetements'),
(1734, 'Scotch Shrunk', 'enfant', 'chaussures'),
(1735, 'Scotch Shrunk', 'enfant', 'sacs'),
(1736, 'Scotch Shrunk', 'enfant', 'accessoires'),
(1737, 'Tocoto Vintage', 'enfant', 'vetements'),
(1738, 'Tocoto Vintage', 'enfant', 'chaussures'),
(1739, 'Tocoto Vintage', 'enfant', 'sacs'),
(1740, 'Tocoto Vintage', 'enfant', 'accessoires'),
(1741, 'Patagonia Kids', 'enfant', 'vetements'),
(1742, 'Patagonia Kids', 'enfant', 'chaussures'),
(1743, 'Patagonia Kids', 'enfant', 'sacs'),
(1744, 'Patagonia Kids', 'enfant', 'accessoires'),
(1745, 'Pom d''Api', 'enfant', 'chaussures'),
(1746, 'Florens', 'enfant', 'chaussures'),
(1747, 'Gallucci', 'enfant', 'chaussures'),
(1748, 'UGG Kids', 'enfant', 'chaussures'),
(1749, 'Veja Kids', 'enfant', 'chaussures'),
(1750, 'Naturino', 'enfant', 'chaussures'),
(1751, 'Geox Kids', 'enfant', 'chaussures'),
(1752, 'Falcotto', 'enfant', 'chaussures'),
(1753, 'Primigi', 'enfant', 'chaussures'),
(1754, 'Bisgaard', 'enfant', 'chaussures'),
(1755, 'Camper Kids', 'enfant', 'chaussures'),
(1756, 'See Kai Run', 'enfant', 'chaussures'),
(1757, 'Stride Rite', 'enfant', 'chaussures'),
(1758, 'Bobux', 'enfant', 'chaussures'),
(1759, 'Start-Rite', 'enfant', 'chaussures'),
(1760, 'Clarks Kids', 'enfant', 'chaussures'),
(1761, 'Superfit', 'enfant', 'chaussures'),
(1762, 'Ricosta', 'enfant', 'chaussures'),
(1763, 'Kavat', 'enfant', 'chaussures'),
(1764, 'Bundgaard', 'enfant', 'chaussures'),
(1765, 'Stonz', 'enfant', 'chaussures'),
(1766, 'Bogs Kids', 'enfant', 'chaussures'),
(1767, 'Hunter Kids', 'enfant', 'chaussures'),
(1768, 'Aigle Kids', 'enfant', 'chaussures'),
(1769, 'Stokke', 'enfant', 'puericulture'),
(1770, 'Bugaboo', 'enfant', 'puericulture'),
(1771, 'Silver Cross', 'enfant', 'puericulture'),
(1772, 'Cybex', 'enfant', 'puericulture'),
(1773, 'Nuna', 'enfant', 'puericulture'),
(1774, 'Doona', 'enfant', 'puericulture'),
(1775, 'Babyzen Yoyo', 'enfant', 'puericulture'),
(1776, 'Joolz', 'enfant', 'puericulture'),
(1777, 'Uppababy', 'enfant', 'puericulture'),
(1778, 'Maxi-Cosi', 'enfant', 'puericulture'),
(1779, 'Inglesina', 'enfant', 'puericulture'),
(1780, 'Peg Perego', 'enfant', 'puericulture'),
(1781, 'Chicco', 'enfant', 'puericulture'),
(1782, 'Joie', 'enfant', 'puericulture'),
(1783, 'Hauck', 'enfant', 'puericulture'),
(1784, 'Graco', 'enfant', 'puericulture'),
(1785, 'Britax Römer', 'enfant', 'puericulture'),
(1786, 'Recaro Kids', 'enfant', 'puericulture'),
(1787, 'Besafe', 'enfant', 'puericulture'),
(1788, 'Ergobaby', 'enfant', 'puericulture'),
(1789, 'BabyBjörn', 'enfant', 'puericulture'),
(1790, 'Manduca', 'enfant', 'puericulture'),
(1791, 'Stokke Tripp Trapp', 'enfant', 'puericulture'),
(1792, 'Leander', 'enfant', 'mobilier'),
(1793, 'Natart', 'enfant', 'mobilier'),
(1794, 'Steiff', 'enfant', 'jouets'),
(1795, 'Jellycat', 'enfant', 'jouets'),
(1796, 'Maileg', 'enfant', 'jouets'),
(1797, 'Moulin Roty', 'enfant', 'jouets'),
(1798, 'Le Toy Van', 'enfant', 'jouets'),
(1799, 'Plan Toys', 'enfant', 'jouets'),
(1800, 'Haba', 'enfant', 'jouets'),
(1801, 'Vilac', 'enfant', 'jouets'),
(1802, 'Djeco', 'enfant', 'jouets'),
(1803, 'Egmont Toys', 'enfant', 'jouets'),
(1804, 'Kaloo', 'enfant', 'jouets'),
(1805, 'Doudou et Compagnie', 'enfant', 'jouets'),
(1806, 'Corolle', 'enfant', 'jouets'),
(1807, 'Götz', 'enfant', 'jouets'),
(1808, 'Käthe Kruse', 'enfant', 'jouets'),
(1809, 'Lego', 'enfant', 'jouets'),
(1810, 'Playmobil', 'enfant', 'jouets'),
(1811, 'Schleich', 'enfant', 'jouets'),
(1812, 'Brio', 'enfant', 'jouets'),
(1813, 'Melissa & Doug', 'enfant', 'jouets'),
(1814, 'Ravensburger', 'enfant', 'jouets'),
(1815, 'Clementoni', 'enfant', 'jouets'),
(1816, 'Orchard Toys', 'enfant', 'jouets'),
(1817, 'eeBoo', 'enfant', 'jouets'),
(1818, 'Toniebox', 'enfant', 'jouets'),
(1819, 'Lunii', 'enfant', 'jouets'),
(1820, 'Yoto', 'enfant', 'jouets'),
(1821, 'KiwiCo', 'enfant', 'jouets'),
(1822, 'Osmo', 'enfant', 'jouets'),
(1823, 'Gallimard Jeunesse', 'enfant', 'scolaire'),
(1824, 'Bayard Jeunesse', 'enfant', 'scolaire'),
(1825, 'École des Loisirs', 'enfant', 'scolaire'),
(1826, 'Albin Michel Jeunesse', 'enfant', 'scolaire'),
(1827, 'Nathan', 'enfant', 'scolaire'),
(1828, 'Larousse Jeunesse', 'enfant', 'scolaire'),
(1829, 'Casterman', 'enfant', 'scolaire'),
(1830, 'Usborne', 'enfant', 'scolaire'),
(1831, 'Dorling Kindersley', 'enfant', 'scolaire');

