-- Marques bébé manquantes : chaussures & accessoires (aucune en base avant cette migration)
-- ids 1832..1881

INSERT INTO public.brands (id, name, gender, type) VALUES
-- Chaussures bébé
(1832, 'Petit Bateau', 'bebe', 'chaussures'),
(1833, 'Chicco', 'bebe', 'chaussures'),
(1834, 'Okaïdi', 'bebe', 'chaussures'),
(1835, 'Vertbaudet', 'bebe', 'chaussures'),
(1836, 'Sergent Major', 'bebe', 'chaussures'),
(1837, 'Jacadi', 'bebe', 'chaussures'),
(1838, 'Absorba', 'bebe', 'chaussures'),
(1839, 'Kiabi', 'bebe', 'chaussures'),
(1840, 'Gémo', 'bebe', 'chaussures'),
(1841, 'C&A', 'bebe', 'chaussures'),
(1842, 'Decathlon', 'bebe', 'chaussures'),
(1843, 'Adidas', 'bebe', 'chaussures'),
(1844, 'Puma', 'bebe', 'chaussures'),
(1845, 'Nike', 'bebe', 'chaussures'),
(1846, 'Converse', 'bebe', 'chaussures'),
(1847, 'Kickers', 'bebe', 'chaussures'),
(1848, 'Geox', 'bebe', 'chaussures'),
(1849, 'Naturino', 'bebe', 'chaussures'),
(1850, 'Primigi', 'bebe', 'chaussures'),
(1851, 'Robeez', 'bebe', 'chaussures'),
(1852, 'Clarks', 'bebe', 'chaussures'),
(1853, 'IKKS Baby', 'bebe', 'chaussures'),
(1854, 'Ralph Lauren Baby', 'bebe', 'chaussures'),
(1855, 'Tommy Hilfiger Baby', 'bebe', 'chaussures'),
(1856, 'Tape à l''œil', 'bebe', 'chaussures'),
(1857, 'Bobux', 'bebe', 'chaussures'),
(1858, 'Camper', 'bebe', 'chaussures'),
-- Accessoires bébé
(1859, 'Petit Bateau', 'bebe', 'accessoires'),
(1860, 'Chicco', 'bebe', 'accessoires'),
(1861, 'Okaïdi', 'bebe', 'accessoires'),
(1862, 'Vertbaudet', 'bebe', 'accessoires'),
(1863, 'Sergent Major', 'bebe', 'accessoires'),
(1864, 'Jacadi', 'bebe', 'accessoires'),
(1865, 'Absorba', 'bebe', 'accessoires'),
(1866, 'Kiabi', 'bebe', 'accessoires'),
(1867, 'Gémo', 'bebe', 'accessoires'),
(1868, 'C&A', 'bebe', 'accessoires'),
(1869, 'Decathlon', 'bebe', 'accessoires'),
(1870, 'Disney Baby', 'bebe', 'accessoires'),
(1871, 'IKKS Baby', 'bebe', 'accessoires'),
(1872, 'Lili Gaufrette', 'bebe', 'accessoires'),
(1873, 'Ralph Lauren Baby', 'bebe', 'accessoires'),
(1874, 'Tommy Hilfiger Baby', 'bebe', 'accessoires'),
(1875, 'United Colors of Benetton Baby', 'bebe', 'accessoires'),
(1876, 'Tape à l''œil', 'bebe', 'accessoires'),
(1877, 'LEGO Wear Baby', 'bebe', 'accessoires'),
(1878, 'Barbie', 'bebe', 'accessoires'),
(1879, 'Levi''s Baby', 'bebe', 'accessoires'),
(1880, 'Playmobil Baby', 'bebe', 'accessoires'),
(1881, 'Puma Baby', 'bebe', 'accessoires');

SELECT setval('brands_id_seq', (SELECT MAX(id) FROM public.brands), true);
