import type { CguContent } from './types';

export const CGU_CONTENT_FR: CguContent = {
  pageTitle: "Conditions générales d'utilisation et de vente",
  effectiveDate: "En vigueur à compter du 13 avril 2026",
  blocks: [
    { type: 'paragraph', text: "Bloomi a été conçu pour rendre la seconde main locale simple, sécurisée et humaine en Suisse. Les présentes Conditions générales d'utilisation et de vente (« CGU ») définissent les règles applicables à l'accès à la plateforme, à la publication d'annonces, aux achats, aux ventes, aux paiements, aux livraisons, aux retours et aux services payants." },
    { type: 'paragraph', text: "En créant un compte, en naviguant sur Bloomi, en publiant une annonce ou en réalisant une transaction, l'utilisateur confirme avoir lu, compris et accepté les présentes CGU ainsi que les politiques auxquelles elles renvoient." },
    { type: 'bullet', text: "Contact : contact@bloomi.ch" },
    { type: 'articleTitle', text: "1. Identité et rôle de Bloomi" },
    { type: 'h2', text: "1.1 Exploitant" },
    { type: 'paragraph', text: "La plateforme Bloomi est exploitée par :" },
    { type: 'bullet', text: "• Raison sociale : Bloomi Sàrl" },
    { type: 'bullet', text: "• Numéro IDE : CHE-356.866.102" },
    { type: 'bullet', text: "• Siège : 1091 Grandvaux, Suisse" },
    { type: 'bullet', text: "• E-mail : contact@bloomi.ch" },
    { type: 'bullet', text: "• Site : www.bloomi.ch" },
    { type: 'h2', text: "1.2 Plateforme d'intermédiation" },
    { type: 'paragraph', text: "Bloomi fournit une infrastructure numérique permettant aux utilisateurs de publier des annonces, de communiquer, de conclure des ventes et d'utiliser les services de paiement et de livraison proposés sur la plateforme." },
    { type: 'paragraph', text: "Sauf lorsqu'elle fournit expressément un service en son propre nom, Bloomi n'est ni le vendeur, ni l'acheteur, ni le propriétaire, ni le dépositaire, ni l'importateur des articles. Le contrat de vente est conclu exclusivement entre le vendeur et l'acheteur." },
    { type: 'paragraph', text: "Bloomi ne procède pas à une inspection physique ou à une authentification systématique des articles et ne garantit pas leur existence, leur origine, leur propriété, leur authenticité, leur légalité, leur qualité, leur sécurité, leur état ou leur conformité à l'annonce." },
    { type: 'paragraph', text: "Bloomi conserve toutefois le droit, sans obligation générale de surveillance, de contrôler une annonce, demander des justificatifs, masquer ou supprimer un contenu, suspendre une transaction, limiter un versement dans les limites autorisées par le prestataire de paiement, restreindre un compte ou coopérer avec les autorités." },
    { type: 'articleTitle', text: "2. Accès à Bloomi et comptes utilisateurs" },
    { type: 'h2', text: "2.1 Capacité juridique" },
    { type: 'paragraph', text: "Bloomi est destiné aux personnes physiques disposant de la capacité juridique nécessaire. Toute personne mineure doit obtenir l'accord préalable de son représentant légal et utiliser Bloomi sous sa responsabilité. Bloomi peut restreindre certaines fonctions, notamment les paiements et versements, lorsque la loi ou le prestataire de paiement l'exige." },
    { type: 'h2', text: "2.2 Catégories de vendeurs" },
    { type: 'bullet', text: "• Vendeurs particuliers (C2C) : les présentes CGU et la politique de protection acheteur s'appliquent." },
    { type: 'bullet', text: "• Vendeurs professionnels ou boutiques (B2C) : ils doivent indiquer clairement leur qualité professionnelle et respecter les obligations légales applicables, y compris leurs propres conditions de vente, garanties et retours. Bloomi peut recevoir et traiter des signalements concernant une boutique professionnelle, retirer une annonce ou suspendre un compte, même lorsqu'elle n'est pas partie au contrat de vente." },
    { type: 'h2', text: "2.3 Création et sécurité du compte" },
    { type: 'paragraph', text: "L'utilisateur doit fournir des informations exactes, complètes et à jour, notamment son identité, sa date de naissance, son téléphone et son e-mail." },
    { type: 'bullet', text: "• Un seul compte personnel est autorisé par personne, sauf autorisation écrite de Bloomi." },
    { type: 'bullet', text: "• Les identifiants sont strictement personnels et doivent rester confidentiels." },
    { type: 'bullet', text: "• Toute activité réalisée depuis le compte est présumée effectuée par son titulaire, sauf preuve contraire." },
    { type: 'bullet', text: "• L'utilisateur doit avertir immédiatement Bloomi en cas d'accès non autorisé ou de suspicion de fraude." },
    { type: 'h2', text: "2.4 Vérifications" },
    { type: 'paragraph', text: "Bloomi ou son prestataire de paiement peut demander tout document raisonnablement nécessaire pour vérifier l'identité, l'âge, l'adresse, les coordonnées bancaires, la capacité juridique, la qualité professionnelle, l'origine d'un article ou la licéité d'une transaction." },
    { type: 'paragraph', text: "Les documents de vérification de paiement sont principalement traités par le prestataire de paiement. Bloomi peut recevoir les informations et statuts nécessaires à l'exploitation de la plateforme, selon la configuration technique et contractuelle applicable." },
    { type: 'h2', text: "2.5 Comptes interdits et contournement" },
    { type: 'paragraph', text: "Il est notamment interdit :" },
    { type: 'bullet', text: "• de créer un compte sous une fausse identité ou pour le compte d'une personne non autorisée ;" },
    { type: 'bullet', text: "• de créer un nouveau compte pour contourner une suspension, une restriction ou une dette ;" },
    { type: 'bullet', text: "• d'utiliser plusieurs comptes pour manipuler les avis, les ventes, les promotions ou les réclamations ;" },
    { type: 'bullet', text: "• de céder, vendre ou louer son compte à un tiers." },
    { type: 'h2', text: "2.6 Suspension et fermeture" },
    { type: 'paragraph', text: "Bloomi peut avertir, limiter, suspendre ou fermer un compte en cas de fraude présumée, violation des CGU, comportement abusif, risque pour les utilisateurs, obligation légale ou demande d'un prestataire compétent. En cas d'urgence ou de risque sérieux, la mesure peut être prise sans préavis." },
    { type: 'articleTitle', text: "3. Articles autorisés et interdits" },
    { type: 'h2', text: "3.1 Articles autorisés" },
    { type: 'paragraph', text: "Bloomi est principalement dédié à la mode de seconde main. Peuvent notamment être proposés :" },
    { type: 'bullet', text: "• vêtements neufs ou d'occasion ;" },
    { type: 'bullet', text: "• chaussures ;" },
    { type: 'bullet', text: "• sacs, ceintures et accessoires de maroquinerie ;" },
    { type: 'bullet', text: "• bijoux fantaisie, montres et accessoires de mode ;" },
    { type: 'bullet', text: "• lunettes ;" },
    { type: 'bullet', text: "• jouets et livres pour enfants, lorsque la catégorie est disponible dans l'application." },
    { type: 'h2', text: "3.2 Articles strictement interdits" },
    { type: 'paragraph', text: "Il est interdit de proposer notamment :" },
    { type: 'bullet', text: "• tout bien dont la vente, la possession, l'importation ou l'exportation est illégale en Suisse ;" },
    { type: 'bullet', text: "• les contrefaçons, répliques illicites, faux, articles volés ou d'origine douteuse ;" },
    { type: 'bullet', text: "• les armes, munitions, explosifs, stupéfiants et substances illicites ;" },
    { type: 'bullet', text: "• les médicaments, dispositifs médicaux réglementés, compléments ou produits soumis à prescription ;" },
    { type: 'bullet', text: "• les denrées alimentaires et boissons, sauf autorisation expresse de Bloomi ;" },
    { type: 'bullet', text: "• les cosmétiques, parfums ou produits d'hygiène ouverts, utilisés, altérés ou non conformes ;" },
    { type: 'bullet', text: "• les produits dangereux, rappelés, défectueux ou ne respectant pas les normes de sécurité applicables ;" },
    { type: 'bullet', text: "• les espèces protégées, fourrures ou matières dont le commerce est interdit ou réglementé sans justificatif ;" },
    { type: 'bullet', text: "• les cartes-cadeaux, moyens de paiement, titres, documents officiels, données personnelles ou comptes numériques ;" },
    { type: 'bullet', text: "• les contenus numériques piratés, licences non transférables ou biens portant atteinte aux droits d'un tiers ;" },
    { type: 'bullet', text: "• tout contenu haineux, discriminatoire, violent, sexuel, trompeur ou portant atteinte à la dignité d'une personne." },
    { type: 'paragraph', text: "Cette liste n'est pas exhaustive. Bloomi peut retirer tout article qui présente un risque juridique, financier, réputationnel ou de sécurité, ou qui enfreint les règles d'un prestataire de paiement ou de livraison." },
    { type: 'articleTitle', text: "4. Annonces et obligations du vendeur" },
    { type: 'h2', text: "4.1 Garanties du vendeur" },
    { type: 'paragraph', text: "En publiant une annonce, le vendeur garantit :" },
    { type: 'bullet', text: "• être propriétaire de l'article ou dûment autorisé à le vendre ;" },
    { type: 'bullet', text: "• que l'article existe, est disponible et peut être légalement vendu ;" },
    { type: 'bullet', text: "• que l'article n'est ni volé, ni contrefait, ni grevé d'un droit appartenant à un tiers ;" },
    { type: 'bullet', text: "• que la marque, la taille, la matière, la couleur, l'état et les photographies sont exacts ;" },
    { type: 'bullet', text: "• que tous les défauts, réparations, transformations, pièces manquantes et signes d'usure importants sont clairement signalés ;" },
    { type: 'bullet', text: "• que le prix et la disponibilité ne sont pas manipulés ;" },
    { type: 'bullet', text: "• conserver les justificatifs utiles jusqu'à la clôture définitive de la transaction." },
    { type: 'h2', text: "4.2 Photos et contenus" },
    { type: 'paragraph', text: "Le vendeur doit utiliser des photographies réelles de l'article proposé. Les visuels générés par intelligence artificielle, les photos trompeuses, les photos prises sur un site marchand ou appartenant à un tiers sont interdits sauf si le vendeur dispose des droits nécessaires et si l'utilisation n'est pas susceptible d'induire l'acheteur en erreur." },
    { type: 'paragraph', text: "L'utilisateur garantit que ses contenus ne violent aucun droit d'auteur, droit à l'image, droit des marques, droit de la personnalité ou autre droit de tiers." },
    { type: 'h2', text: "4.3 Disponibilité" },
    { type: 'paragraph', text: "Le vendeur doit retirer sans délai une annonce lorsque l'article n'est plus disponible. Les annulations répétées ou l'absence répétée d'expédition peuvent entraîner une limitation ou une suspension du compte." },
    { type: 'articleTitle', text: "5. Articles de marque, luxe et authenticité" },
    { type: 'h2', text: "5.1 Interdiction des contrefaçons" },
    { type: 'paragraph', text: "La vente, l'offre, la promotion ou la mise en circulation d'un article contrefait, falsifié, volé ou présenté de manière trompeuse comme authentique est strictement interdite." },
    { type: 'paragraph', text: "Les mentions « réplique », « copie », « inspiré de », « même usine » ou toute formule équivalente ne rendent pas licite un article qui reproduit illicitement une marque, un logo, un modèle ou un autre droit appartenant à un tiers." },
    { type: 'h2', text: "5.2 Justificatifs" },
    { type: 'paragraph', text: "Le vendeur d'un article de marque ou de luxe doit être en mesure de fournir à première demande des éléments permettant d'en établir l'origine et l'authenticité, tels qu'une preuve d'achat, des photographies complémentaires, un numéro de série ou tout autre document pertinent. Bloomi peut juger ces éléments insuffisants ou incohérents et retirer l'annonce." },
    { type: 'h2', text: "5.3 Absence d'authentification systématique" },
    { type: 'paragraph', text: "Sauf indication expresse affichée pour une transaction déterminée, Bloomi ne fournit actuellement aucun service d'authentification et ne certifie pas l'authenticité des articles. La présence d'une annonce sur Bloomi, sa modération ou l'autorisation d'une transaction ne constitue pas une garantie d'authenticité." },
    { type: 'paragraph', text: "Bloomi pourra proposer ultérieurement un service d'authentification distinct, soumis à des conditions particulières. Tant que ce service n'est pas expressément sélectionné et confirmé pour une transaction, aucune authentification par Bloomi ne doit être présumée." },
    { type: 'h2', text: "5.4 Mesures en cas de suspicion" },
    { type: 'paragraph', text: "En cas de suspicion raisonnable, Bloomi peut retirer l'annonce, suspendre la transaction ou le compte, demander des preuves, bloquer temporairement un versement lorsque cela est permis, conserver les éléments nécessaires à l'enquête et effectuer tout signalement légalement requis." },
    { type: 'articleTitle', text: "6. Conclusion et déroulement d'une transaction" },
    { type: 'h2', text: "6.1 Contrat de vente" },
    { type: 'paragraph', text: "Le contrat de vente est conclu directement entre le vendeur et l'acheteur lorsque le paiement est confirmé. Bloomi fournit les outils techniques mais n'est pas partie à ce contrat." },
    { type: 'h2', text: "6.2 Informations avant commande" },
    { type: 'paragraph', text: "Avant de confirmer la commande, l'acheteur doit vérifier l'article, le prix, les frais applicables, la livraison et le montant total à payer. L'acheteur doit vérifier et corriger toute erreur avant validation." },
    { type: 'h2', text: "6.3 Expédition" },
    { type: 'paragraph', text: "Le vendeur dispose de quatre jours ouvrables maximum à compter de la notification de paiement pour expédier l'article, sauf délai différent affiché dans l'application. En l'absence d'expédition dans le délai, Bloomi peut annuler la commande et rembourser l'acheteur." },
    { type: 'h2', text: "6.4 Validation de la vente" },
    { type: 'paragraph', text: "La transaction est validée lorsque l'acheteur confirme la réception. À défaut, elle peut être automatiquement validée quarante-huit heures après l'enregistrement de la livraison par le transporteur, sauf réclamation ouverte dans les délais." },
    { type: 'h2', text: "6.5 Annulation" },
    { type: 'paragraph', text: "Bloomi peut annuler une transaction en cas de non-expédition, article indisponible, erreur technique, risque de fraude, obligation légale, contrôle du prestataire de paiement ou violation des présentes CGU." },
    { type: 'articleTitle', text: "7. Paiements, versements et rétrofacturations" },
    { type: 'h2', text: "7.1 Prestataire de paiement" },
    { type: 'paragraph', text: "Les paiements et versements sont traités par un prestataire de services de paiement externe, actuellement Stripe selon la configuration applicable. L'utilisateur accepte également les conditions et contrôles de ce prestataire." },
    { type: 'paragraph', text: "Le prestataire peut demander des informations, retarder ou refuser une opération, bloquer temporairement des fonds ou imposer des contrôles réglementaires. Bloomi n'a pas le pouvoir de garantir l'acceptation ou le délai exact d'une opération." },
    { type: 'h2', text: "7.2 Versements au vendeur" },
    { type: 'paragraph', text: "Après validation de la transaction, les fonds sont rendus disponibles selon le calendrier et les conditions du prestataire de paiement. Les délais indicatifs affichés dans l'application peuvent varier en raison des contrôles, week-ends, jours fériés, banques ou incidents techniques." },
    { type: 'h2', text: "7.3 Rétrofacturations et paiements contestés" },
    { type: 'paragraph', text: "Lorsqu'un paiement est annulé, contesté, remboursé ou fait l'objet d'une rétrofacturation, Bloomi peut, dans les limites permises par la loi et les conditions du prestataire : suspendre le versement correspondant, compenser une somme avec un solde futur, demander le remboursement d'un montant versé à tort ou restreindre le compte jusqu'à régularisation." },
    { type: 'paragraph', text: "L'utilisateur doit coopérer et fournir les documents nécessaires au traitement de la contestation." },
    { type: 'articleTitle', text: "8. Frais, commissions et services payants" },
    { type: 'h2', text: "8.1 Frais vendeur" },
    { type: 'paragraph', text: "Les frais vendeur sont déduits automatiquement du versement au vendeur :" },
    { type: 'bullet', text: "• 0–100 CHF : 8 % (ex. article à 50 CHF → 4.00 CHF)" },
    { type: 'bullet', text: "• 101–200 CHF : 7 % (ex. article à 150 CHF → 10.50 CHF)" },
    { type: 'bullet', text: "• 201 CHF et plus : 5 % (ex. article à 300 CHF → 15.00 CHF)" },
    { type: 'h2', text: "8.2 Frais acheteur" },
    { type: 'paragraph', text: "Les frais acheteur sont ajoutés au prix de l'article et affichés avant la confirmation de la commande. Ils comprennent une protection acheteur variable et 3 % de frais de service liés au traitement du paiement :" },
    { type: 'bullet', text: "• 0–100 CHF : 12 % protection + 3 % service = 15 % (ex. 50 CHF → 57.50 CHF)" },
    { type: 'bullet', text: "• 101–200 CHF : 10 % protection + 3 % service = 13 % (ex. 150 CHF → 169.50 CHF)" },
    { type: 'bullet', text: "• 201 CHF et plus : 8 % protection + 3 % service = 11 % (ex. 300 CHF → 333.00 CHF)" },
    { type: 'h2', text: "8.3 Mises en avant" },
    { type: 'paragraph', text: "Une mise en avant améliore la visibilité pendant la durée indiquée mais ne garantit aucun nombre de vues, de contacts ni de ventes. Une mise en avant commencée n'est pas remboursable en raison d'une absence de vente, sauf indisponibilité substantielle du service imputable à Bloomi ou droit impératif contraire." },
    { type: 'paragraph', text: "Tarifs indicatifs des mises en avant :" },
    { type: 'bullet', text: "• Pièce unique — 3 jours : 3.00 CHF" },
    { type: 'bullet', text: "• Pièce unique — 7 jours : 5.00 CHF" },
    { type: 'bullet', text: "• Dressing — 3 jours : 5.00 CHF" },
    { type: 'bullet', text: "• Dressing — 7 jours : 9.00 CHF" },
    { type: 'h2', text: "8.4 Modification des frais" },
    { type: 'paragraph', text: "Les frais applicables sont ceux présentés immédiatement avant la confirmation de la transaction. Bloomi peut modifier les frais pour les transactions futures après information des utilisateurs. Aucune modification ne s'applique rétroactivement à une transaction déjà confirmée." },
    { type: 'articleTitle', text: "9. Livraison et remise en main propre" },
    { type: 'h2', text: "9.1 Livraison suivie" },
    { type: 'paragraph', text: "Lorsque la livraison postale est choisie, le vendeur doit utiliser le mode d'envoi indiqué, emballer correctement l'article, vérifier l'adresse et conserver la preuve de dépôt jusqu'à la clôture définitive." },
    { type: 'paragraph', text: "Le suivi du transporteur constitue un moyen de preuve de l'expédition et de la livraison, sans exclure la possibilité de démontrer une erreur manifeste." },
    { type: 'h2', text: "9.2 Répartition des responsabilités" },
    { type: 'bullet', text: "• Une erreur dans l'adresse fournie par l'acheteur lui incombe, sauf faute du vendeur ou de Bloomi." },
    { type: 'bullet', text: "• Un emballage insuffisant, une adresse mal recopiée ou un dépôt hors délai incombe au vendeur." },
    { type: 'bullet', text: "• Les indemnisations pour perte ou dommage sont soumises aux conditions et plafonds du transporteur." },
    { type: 'h2', text: "9.3 Remise en main propre" },
    { type: 'paragraph', text: "La remise en main propre est organisée directement entre l'acheteur et le vendeur. Les parties doivent privilégier un lieu public et confirmer la remise dans l'application au moyen du mécanisme prévu." },
    { type: 'paragraph', text: "Bloomi ne participe pas au rendez-vous et n'est pas responsable des faits survenus pendant celui-ci, sous réserve de ses propres obligations légales." },
    { type: 'articleTitle', text: "10. Protection acheteur et retours entre particuliers" },
    { type: 'clause', text: "PRINCIPE ESSENTIEL : ENTRE PARTICULIERS, IL N'EXISTE PAS DE DROIT GÉNÉRAL AU RETOUR POUR SIMPLE CHANGEMENT D'AVIS. LA PROTECTION BLOOMI EST UN MÉCANISME CONTRACTUEL LIMITÉ AUX CAS DÉFINIS CI-DESSOUS." },
    { type: 'h2', text: "10.1 Motifs recevables" },
    { type: 'bullet', text: "• article substantiellement différent de l'annonce ;" },
    { type: 'bullet', text: "• défaut important existant avant l'envoi et non annoncé ;" },
    { type: 'bullet', text: "• mauvais article reçu ;" },
    { type: 'bullet', text: "• éléments sérieux indiquant une contrefaçon ;" },
    { type: 'bullet', text: "• colis vide ou contenu manifestement incomplet ;" },
    { type: 'bullet', text: "• dommage causé par un emballage manifestement insuffisant." },
    { type: 'h2', text: "10.2 Motifs exclus" },
    { type: 'bullet', text: "• changement d'avis ;" },
    { type: 'bullet', text: "• taille ou coupe ne convenant pas lorsque la taille annoncée est exacte ;" },
    { type: 'bullet', text: "• légère différence de couleur selon l'écran ou l'éclairage ;" },
    { type: 'bullet', text: "• odeur légère ou subjective propre à un article de seconde main ;" },
    { type: 'bullet', text: "• défaut ou usure clairement visible ou mentionné ;" },
    { type: 'bullet', text: "• imperfection mineure compatible avec l'état annoncé ;" },
    { type: 'bullet', text: "• dommage survenu après la livraison ;" },
    { type: 'bullet', text: "• article porté, lavé, réparé, modifié ou dont une étiquette a été retirée ;" },
    { type: 'bullet', text: "• absence d'un accessoire non inclus dans l'annonce." },
    { type: 'h2', text: "10.3 Délai" },
    { type: 'paragraph', text: "L'acheteur doit ouvrir la réclamation depuis la commande dans les vingt-quatre heures suivant la première des dates suivantes : (i) sa confirmation de réception ou (ii) l'enregistrement de la livraison par le transporteur. Passé ce délai, la transaction peut être définitivement validée, sous réserve des droits impératifs applicables." },
    { type: 'h2', text: "10.4 Preuves et conservation" },
    { type: 'paragraph', text: "La réclamation doit comporter une description précise et des photographies claires de l'article, de l'emballage, de l'étiquette d'expédition et du défaut allégué. Bloomi peut demander une vidéo, une preuve d'achat, des photographies supplémentaires ou tout autre élément utile." },
    { type: 'paragraph', text: "L'acheteur doit conserver l'article, l'emballage et les accessoires dans l'état de réception et ne pas porter, laver, réparer, modifier, céder ou revendre l'article pendant l'examen." },
    { type: 'h2', text: "10.5 Gestion administrative limitée" },
    { type: 'paragraph', text: "Bloomi peut effectuer une gestion administrative limitée sur la base des éléments disponibles. Bloomi n'agit ni comme tribunal, ni comme expert, ni comme arbitre et ne réalise pas nécessairement d'inspection physique." },
    { type: 'paragraph', text: "Bloomi peut demander des informations, accepter ou refuser une demande, autoriser un retour, proposer une solution amiable, suspendre temporairement un versement, rembourser ou libérer les fonds selon la procédure applicable." },
    { type: 'h2', text: "10.6 Retour autorisé" },
    { type: 'paragraph', text: "Lorsque le retour est autorisé :" },
    { type: 'bullet', text: "• l'acheteur doit expédier l'article dans le délai indiqué ;" },
    { type: 'bullet', text: "• il doit utiliser l'étiquette et le mode d'expédition indiqués par Bloomi ;" },
    { type: 'bullet', text: "• il doit renvoyer exactement le même article, complet et dans l'état reçu ;" },
    { type: 'bullet', text: "• il doit conserver la preuve de dépôt." },
    { type: 'paragraph', text: "En cas de non-respect, Bloomi peut clôturer la demande et libérer les fonds au vendeur." },
    { type: 'h2', text: "10.7 Réception du retour" },
    { type: 'paragraph', text: "Le retour est considéré comme reçu lorsque le suivi indique sa livraison. Le vendeur dispose alors de vingt-quatre heures pour signaler, preuves à l'appui, que le retour est incomplet, endommagé, substitué ou non conforme. Sans contestation documentée dans ce délai, le remboursement peut être automatiquement déclenché." },
    { type: 'h2', text: "10.8 Remboursement et frais" },
    { type: 'paragraph', text: "Sauf exigence légale contraire, le remboursement porte sur le prix de l'article. Les frais de livraison initiale, les frais de retour et les frais correspondant à des services déjà exécutés ne sont remboursés que dans les cas indiqués avant la commande ou lorsque la cause du retour est imputable au vendeur." },
    { type: 'articleTitle', text: "11. Fraude, abus et transactions hors plateforme" },
    { type: 'h2', text: "11.1 Comportements interdits" },
    { type: 'bullet', text: "• envoyer un colis vide, un autre article ou un article volontairement endommagé ;" },
    { type: 'bullet', text: "• remplacer l'article avant un retour ;" },
    { type: 'bullet', text: "• faire une fausse déclaration de non-réception, de défaut ou de contrefaçon ;" },
    { type: 'bullet', text: "• modifier ou fabriquer une preuve, une photographie, un document ou une donnée de suivi ;" },
    { type: 'bullet', text: "• organiser une transaction fictive ou manipuler les avis et statistiques ;" },
    { type: 'bullet', text: "• harceler, menacer, discriminer ou usurper l'identité d'une personne ;" },
    { type: 'bullet', text: "• utiliser Bloomi à des fins de blanchiment, fraude bancaire ou autre activité illicite." },
    { type: 'h2', text: "11.2 Contournement de Bloomi" },
    { type: 'paragraph', text: "Il est interdit de contourner les systèmes de paiement ou les commissions de Bloomi en proposant ou acceptant une transaction hors plateforme après un contact établi sur Bloomi." },
    { type: 'paragraph', text: "Les paiements, acomptes, livraisons ou échanges réalisés hors des outils Bloomi ne bénéficient d'aucune protection, aucun suivi ni remboursement de Bloomi." },
    { type: 'h2', text: "11.3 Mesures" },
    { type: 'paragraph', text: "En cas d'indices sérieux de fraude ou d'abus, Bloomi peut suspendre une demande, limiter le compte, demander des justificatifs, retenir temporairement un versement lorsque le cadre de paiement le permet, annuler une transaction et transmettre les informations pertinentes aux autorités, titulaires de droits, transporteurs ou prestataires concernés." },
    { type: 'articleTitle', text: "12. Modération, sanctions et signalements" },
    { type: 'h2', text: "12.1 Mesures possibles" },
    { type: 'bullet', text: "• avertissement ;" },
    { type: 'bullet', text: "• limitation de visibilité ;" },
    { type: 'bullet', text: "• suppression d'une annonce ou d'un contenu ;" },
    { type: 'bullet', text: "• restriction de la messagerie, des achats, ventes ou versements ;" },
    { type: 'bullet', text: "• suspension temporaire ;" },
    { type: 'bullet', text: "• fermeture définitive et prévention de nouveaux comptes ;" },
    { type: 'bullet', text: "• annulation d'une transaction ;" },
    { type: 'bullet', text: "• coopération avec les prestataires ou autorités compétentes." },
    { type: 'paragraph', text: "Lorsque cela est raisonnablement possible et compatible avec la sécurité et la loi, Bloomi indique le motif principal de la mesure et permet à l'utilisateur de présenter ses observations." },
    { type: 'h2', text: "12.2 Signalements" },
    { type: 'paragraph', text: "Tout utilisateur peut signaler une annonce, un compte, un contenu ou une transaction suspecte dans l'application ou à contact@bloomi.ch. Le signalement abusif ou mensonger destiné à nuire est interdit." },
    { type: 'articleTitle', text: "13. Propriété intellectuelle et contenus" },
    { type: 'h2', text: "13.1 Droits de Bloomi" },
    { type: 'paragraph', text: "Le nom Bloomi, le logo, la charte graphique, le design, les textes, bases de données, logiciels et éléments de la plateforme appartiennent à Bloomi Sàrl ou à ses concédants. Toute reproduction, extraction ou exploitation non autorisée est interdite." },
    { type: 'h2', text: "13.2 Licence accordée par l'utilisateur" },
    { type: 'paragraph', text: "L'utilisateur conserve ses droits sur ses contenus. Il accorde à Bloomi, pour le monde entier et pendant la durée nécessaire à l'exploitation du compte et des contenus, une licence non exclusive, gratuite et sous-licenciable aux prestataires techniques permettant d'héberger, reproduire, adapter au format, afficher, distribuer et promouvoir ces contenus sur Bloomi et les canaux de communication de Bloomi." },
    { type: 'paragraph', text: "La suppression d'un compte n'impose pas nécessairement le retrait rétroactif de supports promotionnels déjà publiés, sous réserve des droits impératifs de l'utilisateur." },
    { type: 'articleTitle', text: "14. Données personnelles" },
    { type: 'paragraph', text: "Bloomi traite les données personnelles conformément à la loi fédérale suisse sur la protection des données et à sa Politique de confidentialité, qui fait partie intégrante du cadre contractuel." },
    { type: 'paragraph', text: "La Politique de confidentialité précise notamment les catégories de données, finalités, destinataires, prestataires, transferts internationaux, durées de conservation, droits des personnes, mesures de sécurité et coordonnées de contact." },
    { type: 'paragraph', text: "La fermeture du compte n'entraîne pas nécessairement la suppression immédiate de toutes les données. Bloomi peut conserver les informations nécessaires aux transactions en cours, à la prévention de la fraude, au respect des obligations légales et à l'exercice ou à la défense de droits." },
    { type: 'articleTitle', text: "15. Disponibilité et responsabilité" },
    { type: 'h2', text: "15.1 Disponibilité" },
    { type: 'paragraph', text: "Bloomi s'efforce d'assurer la disponibilité de la plateforme mais ne garantit pas un accès continu et sans erreur. Des interruptions peuvent survenir pour maintenance, sécurité, mise à jour ou incident." },
    { type: 'h2', text: "15.2 Responsabilité propre de Bloomi" },
    { type: 'paragraph', text: "Dans les limites permises par le droit applicable, Bloomi répond uniquement des dommages directs causés par une violation fautive de ses propres obligations contractuelles." },
    { type: 'h2', text: "15.3 Exclusions" },
    { type: 'paragraph', text: "Dans les limites permises par la loi, Bloomi ne répond pas :" },
    { type: 'bullet', text: "• des actes ou omissions des utilisateurs ;" },
    { type: 'bullet', text: "• de la conformité, sécurité, qualité, origine ou authenticité des articles ;" },
    { type: 'bullet', text: "• de la bonne exécution du contrat de vente conclu entre utilisateurs ;" },
    { type: 'bullet', text: "• des informations, photos ou déclarations fournies par les utilisateurs ;" },
    { type: 'bullet', text: "• des retards, pertes ou dommages imputables aux transporteurs ;" },
    { type: 'bullet', text: "• des refus, retards ou blocages imputables au prestataire de paiement ;" },
    { type: 'bullet', text: "• des dommages indirects, pertes de profit, pertes d'opportunité ou atteintes à la réputation qui n'étaient pas raisonnablement prévisibles." },
    { type: 'paragraph', text: "Aucune disposition des CGU n'exclut ou ne limite une responsabilité qui ne peut pas être exclue selon le droit applicable, notamment en cas de faute intentionnelle ou de faute grave lorsque la loi l'interdit." },
    { type: 'h2', text: "15.4 Force majeure" },
    { type: 'paragraph', text: "Bloomi n'est pas responsable d'un retard ou manquement causé par un événement échappant raisonnablement à son contrôle, notamment catastrophe naturelle, panne généralisée, cyberattaque, grève, décision administrative, interruption d'un prestataire essentiel ou défaillance des réseaux." },
    { type: 'articleTitle', text: "16. Responsabilité de l'utilisateur envers Bloomi" },
    { type: 'paragraph', text: "Dans la mesure permise par la loi, l'utilisateur répond des dommages directs, frais raisonnables et réclamations de tiers résultant d'une violation fautive ou intentionnelle de ses obligations, notamment en matière de contrefaçon, fraude, propriété intellectuelle, contenus illicites ou informations trompeuses." },
    { type: 'paragraph', text: "Cette clause ne crée pas une indemnisation illimitée et ne prive pas l'utilisateur de ses droits impératifs." },
    { type: 'articleTitle', text: "17. Fermeture du compte" },
    { type: 'h2', text: "17.1 À l'initiative de l'utilisateur" },
    { type: 'paragraph', text: "L'utilisateur peut demander la fermeture de son compte depuis l'application ou en contactant Bloomi. Le compte ne peut pas être définitivement clôturé tant que des transactions, retours, contestations, rétrofacturations, soldes ou obligations légales doivent être traités." },
    { type: 'h2', text: "17.2 Effets" },
    { type: 'paragraph', text: "La fermeture du compte entraîne la perte d'accès aux fonctionnalités. Certaines données peuvent être conservées pendant la durée nécessaire au respect des obligations légales, à la prévention de la fraude et à l'exercice ou la défense de droits." },
    { type: 'articleTitle', text: "18. Modification des CGU et de la plateforme" },
    { type: 'paragraph', text: "Bloomi peut modifier les présentes CGU pour tenir compte d'une évolution légale, technique, commerciale ou opérationnelle. En cas de modification substantielle, Bloomi informe les utilisateurs par e-mail, notification ou message dans l'application avant l'entrée en vigueur, dans un délai raisonnable." },
    { type: 'paragraph', text: "Les modifications ne s'appliquent pas rétroactivement aux transactions déjà confirmées, sauf exigence légale ou accord des parties." },
    { type: 'articleTitle', text: "19. Dispositions générales" },
    { type: 'h2', text: "19.1 Nullité partielle" },
    { type: 'paragraph', text: "Si une disposition est déclarée invalide ou inapplicable, les autres dispositions restent en vigueur. La disposition concernée est remplacée, dans la mesure permise, par une règle valide se rapprochant de son objectif." },
    { type: 'h2', text: "19.2 Absence de renonciation" },
    { type: 'paragraph', text: "Le fait que Bloomi n'exerce pas immédiatement un droit ne vaut pas renonciation à ce droit." },
    { type: 'h2', text: "19.3 Cession" },
    { type: 'paragraph', text: "L'utilisateur ne peut céder son compte ou ses droits sans l'accord de Bloomi. Bloomi peut transférer les présentes CGU à une entité reprenant tout ou partie de son activité, sous réserve des droits impératifs." },
    { type: 'h2', text: "19.4 Langue" },
    { type: 'paragraph', text: "La version française fait foi, sauf indication contraire. Des traductions peuvent être proposées pour faciliter la compréhension." },
    { type: 'articleTitle', text: "20. Droit applicable et litiges" },
    { type: 'h2', text: "20.1 Droit suisse" },
    { type: 'paragraph', text: "Les présentes CGU et les relations entre Bloomi et ses utilisateurs sont régies par le droit suisse." },
    { type: 'h2', text: "20.2 Réclamation amiable" },
    { type: 'paragraph', text: "Avant toute procédure, l'utilisateur est invité à écrire à contact@bloomi.ch en décrivant précisément la situation et en joignant les justificatifs utiles. Bloomi s'efforcera de rechercher une solution amiable." },
    { type: 'h2', text: "20.3 For" },
    { type: 'paragraph', text: "Sous réserve des fors et dispositions impératives applicables, les tribunaux du canton de Vaud sont compétents." },
    { type: 'articleTitle', text: "21. Contact" },
    { type: 'bullet', text: "• Bloomi Sàrl" },
    { type: 'bullet', text: "• 1091 Grandvaux, Suisse" },
    { type: 'bullet', text: "• E-mail : contact@bloomi.ch" },
    { type: 'bullet', text: "• Site : www.bloomi.ch" },
  ],
  footer: "© 2026 Bloomi Sàrl — CHE-356.866.102 — Tous droits réservés"
};
